// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top,hls_ip_2017_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg225-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.983000,HLS_SYN_LAT=22,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=1,HLS_SYN_FF=1764,HLS_SYN_LUT=2297}" *)

module top (
        stream_in_TDATA,
        stream_in_TUSER,
        stream_in_TLAST,
        stream_out_TDATA,
        stream_out_TUSER,
        stream_out_TLAST,
        ap_clk,
        ap_rst_n,
        stream_in_TVALID,
        stream_in_TREADY,
        stream_out_TVALID,
        stream_out_TREADY
);


input  [23:0] stream_in_TDATA;
input  [0:0] stream_in_TUSER;
input  [0:0] stream_in_TLAST;
output  [23:0] stream_out_TDATA;
output  [0:0] stream_out_TUSER;
output  [0:0] stream_out_TLAST;
input   ap_clk;
input   ap_rst_n;
input   stream_in_TVALID;
output   stream_in_TREADY;
output   stream_out_TVALID;
input   stream_out_TREADY;

reg    ap_rst_n_inv;
wire    BlackWhite_U0_ap_start;
wire    BlackWhite_U0_start_full_n;
wire    BlackWhite_U0_ap_done;
wire    BlackWhite_U0_ap_continue;
wire    BlackWhite_U0_ap_idle;
wire    BlackWhite_U0_ap_ready;
wire    BlackWhite_U0_start_out;
wire    BlackWhite_U0_start_write;
wire    BlackWhite_U0_stream_in_TREADY;
wire   [7:0] BlackWhite_U0_BWStream_V_data_V_din;
wire    BlackWhite_U0_BWStream_V_data_V_write;
wire   [0:0] BlackWhite_U0_BWStream_V_user_V_din;
wire    BlackWhite_U0_BWStream_V_user_V_write;
wire   [0:0] BlackWhite_U0_BWStream_V_last_V_din;
wire    BlackWhite_U0_BWStream_V_last_V_write;
wire    Matrix_U0_ap_start;
wire    Matrix_U0_start_full_n;
wire    Matrix_U0_ap_done;
wire    Matrix_U0_ap_continue;
wire    Matrix_U0_ap_idle;
wire    Matrix_U0_ap_ready;
wire    Matrix_U0_start_out;
wire    Matrix_U0_start_write;
wire    Matrix_U0_BWStream_V_data_V_read;
wire    Matrix_U0_BWStream_V_user_V_read;
wire    Matrix_U0_BWStream_V_last_V_read;
wire   [7:0] Matrix_U0_PxlStream_V_pixel_da_8_din;
wire    Matrix_U0_PxlStream_V_pixel_da_8_write;
wire   [7:0] Matrix_U0_PxlStream_V_pixel_da_7_din;
wire    Matrix_U0_PxlStream_V_pixel_da_7_write;
wire   [7:0] Matrix_U0_PxlStream_V_pixel_da_6_din;
wire    Matrix_U0_PxlStream_V_pixel_da_6_write;
wire   [7:0] Matrix_U0_PxlStream_V_pixel_da_5_din;
wire    Matrix_U0_PxlStream_V_pixel_da_5_write;
wire   [7:0] Matrix_U0_PxlStream_V_pixel_da_4_din;
wire    Matrix_U0_PxlStream_V_pixel_da_4_write;
wire   [7:0] Matrix_U0_PxlStream_V_pixel_da_3_din;
wire    Matrix_U0_PxlStream_V_pixel_da_3_write;
wire   [7:0] Matrix_U0_PxlStream_V_pixel_da_2_din;
wire    Matrix_U0_PxlStream_V_pixel_da_2_write;
wire   [7:0] Matrix_U0_PxlStream_V_pixel_da_1_din;
wire    Matrix_U0_PxlStream_V_pixel_da_1_write;
wire   [7:0] Matrix_U0_PxlStream_V_pixel_da_din;
wire    Matrix_U0_PxlStream_V_pixel_da_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_us_8_din;
wire    Matrix_U0_PxlStream_V_pixel_us_8_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_us_7_din;
wire    Matrix_U0_PxlStream_V_pixel_us_7_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_us_6_din;
wire    Matrix_U0_PxlStream_V_pixel_us_6_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_us_5_din;
wire    Matrix_U0_PxlStream_V_pixel_us_5_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_us_4_din;
wire    Matrix_U0_PxlStream_V_pixel_us_4_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_us_3_din;
wire    Matrix_U0_PxlStream_V_pixel_us_3_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_us_2_din;
wire    Matrix_U0_PxlStream_V_pixel_us_2_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_us_1_din;
wire    Matrix_U0_PxlStream_V_pixel_us_1_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_us_din;
wire    Matrix_U0_PxlStream_V_pixel_us_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_la_8_din;
wire    Matrix_U0_PxlStream_V_pixel_la_8_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_la_7_din;
wire    Matrix_U0_PxlStream_V_pixel_la_7_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_la_6_din;
wire    Matrix_U0_PxlStream_V_pixel_la_6_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_la_5_din;
wire    Matrix_U0_PxlStream_V_pixel_la_5_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_la_4_din;
wire    Matrix_U0_PxlStream_V_pixel_la_4_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_la_3_din;
wire    Matrix_U0_PxlStream_V_pixel_la_3_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_la_2_din;
wire    Matrix_U0_PxlStream_V_pixel_la_2_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_la_1_din;
wire    Matrix_U0_PxlStream_V_pixel_la_1_write;
wire   [0:0] Matrix_U0_PxlStream_V_pixel_la_din;
wire    Matrix_U0_PxlStream_V_pixel_la_write;
wire    Median_U0_ap_start;
wire    Median_U0_start_full_n;
wire    Median_U0_ap_done;
wire    Median_U0_ap_continue;
wire    Median_U0_ap_idle;
wire    Median_U0_ap_ready;
wire    Median_U0_start_out;
wire    Median_U0_start_write;
wire    Median_U0_PxlStream_V_pixel_da_8_read;
wire    Median_U0_PxlStream_V_pixel_da_7_read;
wire    Median_U0_PxlStream_V_pixel_da_6_read;
wire    Median_U0_PxlStream_V_pixel_da_5_read;
wire    Median_U0_PxlStream_V_pixel_da_4_read;
wire    Median_U0_PxlStream_V_pixel_da_3_read;
wire    Median_U0_PxlStream_V_pixel_da_2_read;
wire    Median_U0_PxlStream_V_pixel_da_1_read;
wire    Median_U0_PxlStream_V_pixel_da_read;
wire    Median_U0_PxlStream_V_pixel_us_8_read;
wire    Median_U0_PxlStream_V_pixel_us_7_read;
wire    Median_U0_PxlStream_V_pixel_us_6_read;
wire    Median_U0_PxlStream_V_pixel_us_5_read;
wire    Median_U0_PxlStream_V_pixel_us_4_read;
wire    Median_U0_PxlStream_V_pixel_us_3_read;
wire    Median_U0_PxlStream_V_pixel_us_2_read;
wire    Median_U0_PxlStream_V_pixel_us_1_read;
wire    Median_U0_PxlStream_V_pixel_us_read;
wire    Median_U0_PxlStream_V_pixel_la_8_read;
wire    Median_U0_PxlStream_V_pixel_la_7_read;
wire    Median_U0_PxlStream_V_pixel_la_6_read;
wire    Median_U0_PxlStream_V_pixel_la_5_read;
wire    Median_U0_PxlStream_V_pixel_la_4_read;
wire    Median_U0_PxlStream_V_pixel_la_3_read;
wire    Median_U0_PxlStream_V_pixel_la_2_read;
wire    Median_U0_PxlStream_V_pixel_la_1_read;
wire    Median_U0_PxlStream_V_pixel_la_read;
wire   [7:0] Median_U0_MdnStream_V_data_V_din;
wire    Median_U0_MdnStream_V_data_V_write;
wire   [0:0] Median_U0_MdnStream_V_user_V_din;
wire    Median_U0_MdnStream_V_user_V_write;
wire   [0:0] Median_U0_MdnStream_V_last_V_din;
wire    Median_U0_MdnStream_V_last_V_write;
wire    Color_U0_ap_start;
wire    Color_U0_ap_done;
wire    Color_U0_ap_continue;
wire    Color_U0_ap_idle;
wire    Color_U0_ap_ready;
wire   [23:0] Color_U0_stream_out_TDATA;
wire    Color_U0_stream_out_TVALID;
wire   [0:0] Color_U0_stream_out_TUSER;
wire   [0:0] Color_U0_stream_out_TLAST;
wire    Color_U0_MdnStream_V_data_V_read;
wire    Color_U0_MdnStream_V_user_V_read;
wire    Color_U0_MdnStream_V_last_V_read;
wire    ap_sync_continue;
wire    BWStream_V_data_V_full_n;
wire   [7:0] BWStream_V_data_V_dout;
wire    BWStream_V_data_V_empty_n;
wire    BWStream_V_user_V_full_n;
wire   [0:0] BWStream_V_user_V_dout;
wire    BWStream_V_user_V_empty_n;
wire    BWStream_V_last_V_full_n;
wire   [0:0] BWStream_V_last_V_dout;
wire    BWStream_V_last_V_empty_n;
wire    PxlStream_V_pixel_da_8_full_n;
wire   [7:0] PxlStream_V_pixel_da_8_dout;
wire    PxlStream_V_pixel_da_8_empty_n;
wire    PxlStream_V_pixel_da_7_full_n;
wire   [7:0] PxlStream_V_pixel_da_7_dout;
wire    PxlStream_V_pixel_da_7_empty_n;
wire    PxlStream_V_pixel_da_6_full_n;
wire   [7:0] PxlStream_V_pixel_da_6_dout;
wire    PxlStream_V_pixel_da_6_empty_n;
wire    PxlStream_V_pixel_da_5_full_n;
wire   [7:0] PxlStream_V_pixel_da_5_dout;
wire    PxlStream_V_pixel_da_5_empty_n;
wire    PxlStream_V_pixel_da_4_full_n;
wire   [7:0] PxlStream_V_pixel_da_4_dout;
wire    PxlStream_V_pixel_da_4_empty_n;
wire    PxlStream_V_pixel_da_3_full_n;
wire   [7:0] PxlStream_V_pixel_da_3_dout;
wire    PxlStream_V_pixel_da_3_empty_n;
wire    PxlStream_V_pixel_da_2_full_n;
wire   [7:0] PxlStream_V_pixel_da_2_dout;
wire    PxlStream_V_pixel_da_2_empty_n;
wire    PxlStream_V_pixel_da_1_full_n;
wire   [7:0] PxlStream_V_pixel_da_1_dout;
wire    PxlStream_V_pixel_da_1_empty_n;
wire    PxlStream_V_pixel_da_full_n;
wire   [7:0] PxlStream_V_pixel_da_dout;
wire    PxlStream_V_pixel_da_empty_n;
wire    PxlStream_V_pixel_us_8_full_n;
wire   [0:0] PxlStream_V_pixel_us_8_dout;
wire    PxlStream_V_pixel_us_8_empty_n;
wire    PxlStream_V_pixel_us_7_full_n;
wire   [0:0] PxlStream_V_pixel_us_7_dout;
wire    PxlStream_V_pixel_us_7_empty_n;
wire    PxlStream_V_pixel_us_6_full_n;
wire   [0:0] PxlStream_V_pixel_us_6_dout;
wire    PxlStream_V_pixel_us_6_empty_n;
wire    PxlStream_V_pixel_us_5_full_n;
wire   [0:0] PxlStream_V_pixel_us_5_dout;
wire    PxlStream_V_pixel_us_5_empty_n;
wire    PxlStream_V_pixel_us_4_full_n;
wire   [0:0] PxlStream_V_pixel_us_4_dout;
wire    PxlStream_V_pixel_us_4_empty_n;
wire    PxlStream_V_pixel_us_3_full_n;
wire   [0:0] PxlStream_V_pixel_us_3_dout;
wire    PxlStream_V_pixel_us_3_empty_n;
wire    PxlStream_V_pixel_us_2_full_n;
wire   [0:0] PxlStream_V_pixel_us_2_dout;
wire    PxlStream_V_pixel_us_2_empty_n;
wire    PxlStream_V_pixel_us_1_full_n;
wire   [0:0] PxlStream_V_pixel_us_1_dout;
wire    PxlStream_V_pixel_us_1_empty_n;
wire    PxlStream_V_pixel_us_full_n;
wire   [0:0] PxlStream_V_pixel_us_dout;
wire    PxlStream_V_pixel_us_empty_n;
wire    PxlStream_V_pixel_la_8_full_n;
wire   [0:0] PxlStream_V_pixel_la_8_dout;
wire    PxlStream_V_pixel_la_8_empty_n;
wire    PxlStream_V_pixel_la_7_full_n;
wire   [0:0] PxlStream_V_pixel_la_7_dout;
wire    PxlStream_V_pixel_la_7_empty_n;
wire    PxlStream_V_pixel_la_6_full_n;
wire   [0:0] PxlStream_V_pixel_la_6_dout;
wire    PxlStream_V_pixel_la_6_empty_n;
wire    PxlStream_V_pixel_la_5_full_n;
wire   [0:0] PxlStream_V_pixel_la_5_dout;
wire    PxlStream_V_pixel_la_5_empty_n;
wire    PxlStream_V_pixel_la_4_full_n;
wire   [0:0] PxlStream_V_pixel_la_4_dout;
wire    PxlStream_V_pixel_la_4_empty_n;
wire    PxlStream_V_pixel_la_3_full_n;
wire   [0:0] PxlStream_V_pixel_la_3_dout;
wire    PxlStream_V_pixel_la_3_empty_n;
wire    PxlStream_V_pixel_la_2_full_n;
wire   [0:0] PxlStream_V_pixel_la_2_dout;
wire    PxlStream_V_pixel_la_2_empty_n;
wire    PxlStream_V_pixel_la_1_full_n;
wire   [0:0] PxlStream_V_pixel_la_1_dout;
wire    PxlStream_V_pixel_la_1_empty_n;
wire    PxlStream_V_pixel_la_full_n;
wire   [0:0] PxlStream_V_pixel_la_dout;
wire    PxlStream_V_pixel_la_empty_n;
wire    MdnStream_V_data_V_full_n;
wire   [7:0] MdnStream_V_data_V_dout;
wire    MdnStream_V_data_V_empty_n;
wire    MdnStream_V_user_V_full_n;
wire   [0:0] MdnStream_V_user_V_dout;
wire    MdnStream_V_user_V_empty_n;
wire    MdnStream_V_last_V_full_n;
wire   [0:0] MdnStream_V_last_V_dout;
wire    MdnStream_V_last_V_empty_n;
wire   [0:0] start_for_Matrix_U0_din;
wire    start_for_Matrix_U0_full_n;
wire   [0:0] start_for_Matrix_U0_dout;
wire    start_for_Matrix_U0_empty_n;
wire   [0:0] start_for_Median_U0_din;
wire    start_for_Median_U0_full_n;
wire   [0:0] start_for_Median_U0_dout;
wire    start_for_Median_U0_empty_n;
wire   [0:0] start_for_Color_U0_din;
wire    start_for_Color_U0_full_n;
wire   [0:0] start_for_Color_U0_dout;
wire    start_for_Color_U0_empty_n;
wire    Color_U0_start_full_n;
wire    Color_U0_start_write;

BlackWhite BlackWhite_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(BlackWhite_U0_ap_start),
    .start_full_n(BlackWhite_U0_start_full_n),
    .ap_done(BlackWhite_U0_ap_done),
    .ap_continue(BlackWhite_U0_ap_continue),
    .ap_idle(BlackWhite_U0_ap_idle),
    .ap_ready(BlackWhite_U0_ap_ready),
    .start_out(BlackWhite_U0_start_out),
    .start_write(BlackWhite_U0_start_write),
    .stream_in_TDATA(stream_in_TDATA),
    .stream_in_TVALID(stream_in_TVALID),
    .stream_in_TREADY(BlackWhite_U0_stream_in_TREADY),
    .stream_in_TUSER(stream_in_TUSER),
    .stream_in_TLAST(stream_in_TLAST),
    .BWStream_V_data_V_din(BlackWhite_U0_BWStream_V_data_V_din),
    .BWStream_V_data_V_full_n(BWStream_V_data_V_full_n),
    .BWStream_V_data_V_write(BlackWhite_U0_BWStream_V_data_V_write),
    .BWStream_V_user_V_din(BlackWhite_U0_BWStream_V_user_V_din),
    .BWStream_V_user_V_full_n(BWStream_V_user_V_full_n),
    .BWStream_V_user_V_write(BlackWhite_U0_BWStream_V_user_V_write),
    .BWStream_V_last_V_din(BlackWhite_U0_BWStream_V_last_V_din),
    .BWStream_V_last_V_full_n(BWStream_V_last_V_full_n),
    .BWStream_V_last_V_write(BlackWhite_U0_BWStream_V_last_V_write)
);

Matrix Matrix_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Matrix_U0_ap_start),
    .start_full_n(Matrix_U0_start_full_n),
    .ap_done(Matrix_U0_ap_done),
    .ap_continue(Matrix_U0_ap_continue),
    .ap_idle(Matrix_U0_ap_idle),
    .ap_ready(Matrix_U0_ap_ready),
    .start_out(Matrix_U0_start_out),
    .start_write(Matrix_U0_start_write),
    .BWStream_V_data_V_dout(BWStream_V_data_V_dout),
    .BWStream_V_data_V_empty_n(BWStream_V_data_V_empty_n),
    .BWStream_V_data_V_read(Matrix_U0_BWStream_V_data_V_read),
    .BWStream_V_user_V_dout(BWStream_V_user_V_dout),
    .BWStream_V_user_V_empty_n(BWStream_V_user_V_empty_n),
    .BWStream_V_user_V_read(Matrix_U0_BWStream_V_user_V_read),
    .BWStream_V_last_V_dout(BWStream_V_last_V_dout),
    .BWStream_V_last_V_empty_n(BWStream_V_last_V_empty_n),
    .BWStream_V_last_V_read(Matrix_U0_BWStream_V_last_V_read),
    .PxlStream_V_pixel_da_8_din(Matrix_U0_PxlStream_V_pixel_da_8_din),
    .PxlStream_V_pixel_da_8_full_n(PxlStream_V_pixel_da_8_full_n),
    .PxlStream_V_pixel_da_8_write(Matrix_U0_PxlStream_V_pixel_da_8_write),
    .PxlStream_V_pixel_da_7_din(Matrix_U0_PxlStream_V_pixel_da_7_din),
    .PxlStream_V_pixel_da_7_full_n(PxlStream_V_pixel_da_7_full_n),
    .PxlStream_V_pixel_da_7_write(Matrix_U0_PxlStream_V_pixel_da_7_write),
    .PxlStream_V_pixel_da_6_din(Matrix_U0_PxlStream_V_pixel_da_6_din),
    .PxlStream_V_pixel_da_6_full_n(PxlStream_V_pixel_da_6_full_n),
    .PxlStream_V_pixel_da_6_write(Matrix_U0_PxlStream_V_pixel_da_6_write),
    .PxlStream_V_pixel_da_5_din(Matrix_U0_PxlStream_V_pixel_da_5_din),
    .PxlStream_V_pixel_da_5_full_n(PxlStream_V_pixel_da_5_full_n),
    .PxlStream_V_pixel_da_5_write(Matrix_U0_PxlStream_V_pixel_da_5_write),
    .PxlStream_V_pixel_da_4_din(Matrix_U0_PxlStream_V_pixel_da_4_din),
    .PxlStream_V_pixel_da_4_full_n(PxlStream_V_pixel_da_4_full_n),
    .PxlStream_V_pixel_da_4_write(Matrix_U0_PxlStream_V_pixel_da_4_write),
    .PxlStream_V_pixel_da_3_din(Matrix_U0_PxlStream_V_pixel_da_3_din),
    .PxlStream_V_pixel_da_3_full_n(PxlStream_V_pixel_da_3_full_n),
    .PxlStream_V_pixel_da_3_write(Matrix_U0_PxlStream_V_pixel_da_3_write),
    .PxlStream_V_pixel_da_2_din(Matrix_U0_PxlStream_V_pixel_da_2_din),
    .PxlStream_V_pixel_da_2_full_n(PxlStream_V_pixel_da_2_full_n),
    .PxlStream_V_pixel_da_2_write(Matrix_U0_PxlStream_V_pixel_da_2_write),
    .PxlStream_V_pixel_da_1_din(Matrix_U0_PxlStream_V_pixel_da_1_din),
    .PxlStream_V_pixel_da_1_full_n(PxlStream_V_pixel_da_1_full_n),
    .PxlStream_V_pixel_da_1_write(Matrix_U0_PxlStream_V_pixel_da_1_write),
    .PxlStream_V_pixel_da_din(Matrix_U0_PxlStream_V_pixel_da_din),
    .PxlStream_V_pixel_da_full_n(PxlStream_V_pixel_da_full_n),
    .PxlStream_V_pixel_da_write(Matrix_U0_PxlStream_V_pixel_da_write),
    .PxlStream_V_pixel_us_8_din(Matrix_U0_PxlStream_V_pixel_us_8_din),
    .PxlStream_V_pixel_us_8_full_n(PxlStream_V_pixel_us_8_full_n),
    .PxlStream_V_pixel_us_8_write(Matrix_U0_PxlStream_V_pixel_us_8_write),
    .PxlStream_V_pixel_us_7_din(Matrix_U0_PxlStream_V_pixel_us_7_din),
    .PxlStream_V_pixel_us_7_full_n(PxlStream_V_pixel_us_7_full_n),
    .PxlStream_V_pixel_us_7_write(Matrix_U0_PxlStream_V_pixel_us_7_write),
    .PxlStream_V_pixel_us_6_din(Matrix_U0_PxlStream_V_pixel_us_6_din),
    .PxlStream_V_pixel_us_6_full_n(PxlStream_V_pixel_us_6_full_n),
    .PxlStream_V_pixel_us_6_write(Matrix_U0_PxlStream_V_pixel_us_6_write),
    .PxlStream_V_pixel_us_5_din(Matrix_U0_PxlStream_V_pixel_us_5_din),
    .PxlStream_V_pixel_us_5_full_n(PxlStream_V_pixel_us_5_full_n),
    .PxlStream_V_pixel_us_5_write(Matrix_U0_PxlStream_V_pixel_us_5_write),
    .PxlStream_V_pixel_us_4_din(Matrix_U0_PxlStream_V_pixel_us_4_din),
    .PxlStream_V_pixel_us_4_full_n(PxlStream_V_pixel_us_4_full_n),
    .PxlStream_V_pixel_us_4_write(Matrix_U0_PxlStream_V_pixel_us_4_write),
    .PxlStream_V_pixel_us_3_din(Matrix_U0_PxlStream_V_pixel_us_3_din),
    .PxlStream_V_pixel_us_3_full_n(PxlStream_V_pixel_us_3_full_n),
    .PxlStream_V_pixel_us_3_write(Matrix_U0_PxlStream_V_pixel_us_3_write),
    .PxlStream_V_pixel_us_2_din(Matrix_U0_PxlStream_V_pixel_us_2_din),
    .PxlStream_V_pixel_us_2_full_n(PxlStream_V_pixel_us_2_full_n),
    .PxlStream_V_pixel_us_2_write(Matrix_U0_PxlStream_V_pixel_us_2_write),
    .PxlStream_V_pixel_us_1_din(Matrix_U0_PxlStream_V_pixel_us_1_din),
    .PxlStream_V_pixel_us_1_full_n(PxlStream_V_pixel_us_1_full_n),
    .PxlStream_V_pixel_us_1_write(Matrix_U0_PxlStream_V_pixel_us_1_write),
    .PxlStream_V_pixel_us_din(Matrix_U0_PxlStream_V_pixel_us_din),
    .PxlStream_V_pixel_us_full_n(PxlStream_V_pixel_us_full_n),
    .PxlStream_V_pixel_us_write(Matrix_U0_PxlStream_V_pixel_us_write),
    .PxlStream_V_pixel_la_8_din(Matrix_U0_PxlStream_V_pixel_la_8_din),
    .PxlStream_V_pixel_la_8_full_n(PxlStream_V_pixel_la_8_full_n),
    .PxlStream_V_pixel_la_8_write(Matrix_U0_PxlStream_V_pixel_la_8_write),
    .PxlStream_V_pixel_la_7_din(Matrix_U0_PxlStream_V_pixel_la_7_din),
    .PxlStream_V_pixel_la_7_full_n(PxlStream_V_pixel_la_7_full_n),
    .PxlStream_V_pixel_la_7_write(Matrix_U0_PxlStream_V_pixel_la_7_write),
    .PxlStream_V_pixel_la_6_din(Matrix_U0_PxlStream_V_pixel_la_6_din),
    .PxlStream_V_pixel_la_6_full_n(PxlStream_V_pixel_la_6_full_n),
    .PxlStream_V_pixel_la_6_write(Matrix_U0_PxlStream_V_pixel_la_6_write),
    .PxlStream_V_pixel_la_5_din(Matrix_U0_PxlStream_V_pixel_la_5_din),
    .PxlStream_V_pixel_la_5_full_n(PxlStream_V_pixel_la_5_full_n),
    .PxlStream_V_pixel_la_5_write(Matrix_U0_PxlStream_V_pixel_la_5_write),
    .PxlStream_V_pixel_la_4_din(Matrix_U0_PxlStream_V_pixel_la_4_din),
    .PxlStream_V_pixel_la_4_full_n(PxlStream_V_pixel_la_4_full_n),
    .PxlStream_V_pixel_la_4_write(Matrix_U0_PxlStream_V_pixel_la_4_write),
    .PxlStream_V_pixel_la_3_din(Matrix_U0_PxlStream_V_pixel_la_3_din),
    .PxlStream_V_pixel_la_3_full_n(PxlStream_V_pixel_la_3_full_n),
    .PxlStream_V_pixel_la_3_write(Matrix_U0_PxlStream_V_pixel_la_3_write),
    .PxlStream_V_pixel_la_2_din(Matrix_U0_PxlStream_V_pixel_la_2_din),
    .PxlStream_V_pixel_la_2_full_n(PxlStream_V_pixel_la_2_full_n),
    .PxlStream_V_pixel_la_2_write(Matrix_U0_PxlStream_V_pixel_la_2_write),
    .PxlStream_V_pixel_la_1_din(Matrix_U0_PxlStream_V_pixel_la_1_din),
    .PxlStream_V_pixel_la_1_full_n(PxlStream_V_pixel_la_1_full_n),
    .PxlStream_V_pixel_la_1_write(Matrix_U0_PxlStream_V_pixel_la_1_write),
    .PxlStream_V_pixel_la_din(Matrix_U0_PxlStream_V_pixel_la_din),
    .PxlStream_V_pixel_la_full_n(PxlStream_V_pixel_la_full_n),
    .PxlStream_V_pixel_la_write(Matrix_U0_PxlStream_V_pixel_la_write)
);

Median Median_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Median_U0_ap_start),
    .start_full_n(Median_U0_start_full_n),
    .ap_done(Median_U0_ap_done),
    .ap_continue(Median_U0_ap_continue),
    .ap_idle(Median_U0_ap_idle),
    .ap_ready(Median_U0_ap_ready),
    .start_out(Median_U0_start_out),
    .start_write(Median_U0_start_write),
    .PxlStream_V_pixel_da_8_dout(PxlStream_V_pixel_da_8_dout),
    .PxlStream_V_pixel_da_8_empty_n(PxlStream_V_pixel_da_8_empty_n),
    .PxlStream_V_pixel_da_8_read(Median_U0_PxlStream_V_pixel_da_8_read),
    .PxlStream_V_pixel_da_7_dout(PxlStream_V_pixel_da_7_dout),
    .PxlStream_V_pixel_da_7_empty_n(PxlStream_V_pixel_da_7_empty_n),
    .PxlStream_V_pixel_da_7_read(Median_U0_PxlStream_V_pixel_da_7_read),
    .PxlStream_V_pixel_da_6_dout(PxlStream_V_pixel_da_6_dout),
    .PxlStream_V_pixel_da_6_empty_n(PxlStream_V_pixel_da_6_empty_n),
    .PxlStream_V_pixel_da_6_read(Median_U0_PxlStream_V_pixel_da_6_read),
    .PxlStream_V_pixel_da_5_dout(PxlStream_V_pixel_da_5_dout),
    .PxlStream_V_pixel_da_5_empty_n(PxlStream_V_pixel_da_5_empty_n),
    .PxlStream_V_pixel_da_5_read(Median_U0_PxlStream_V_pixel_da_5_read),
    .PxlStream_V_pixel_da_4_dout(PxlStream_V_pixel_da_4_dout),
    .PxlStream_V_pixel_da_4_empty_n(PxlStream_V_pixel_da_4_empty_n),
    .PxlStream_V_pixel_da_4_read(Median_U0_PxlStream_V_pixel_da_4_read),
    .PxlStream_V_pixel_da_3_dout(PxlStream_V_pixel_da_3_dout),
    .PxlStream_V_pixel_da_3_empty_n(PxlStream_V_pixel_da_3_empty_n),
    .PxlStream_V_pixel_da_3_read(Median_U0_PxlStream_V_pixel_da_3_read),
    .PxlStream_V_pixel_da_2_dout(PxlStream_V_pixel_da_2_dout),
    .PxlStream_V_pixel_da_2_empty_n(PxlStream_V_pixel_da_2_empty_n),
    .PxlStream_V_pixel_da_2_read(Median_U0_PxlStream_V_pixel_da_2_read),
    .PxlStream_V_pixel_da_1_dout(PxlStream_V_pixel_da_1_dout),
    .PxlStream_V_pixel_da_1_empty_n(PxlStream_V_pixel_da_1_empty_n),
    .PxlStream_V_pixel_da_1_read(Median_U0_PxlStream_V_pixel_da_1_read),
    .PxlStream_V_pixel_da_dout(PxlStream_V_pixel_da_dout),
    .PxlStream_V_pixel_da_empty_n(PxlStream_V_pixel_da_empty_n),
    .PxlStream_V_pixel_da_read(Median_U0_PxlStream_V_pixel_da_read),
    .PxlStream_V_pixel_us_8_dout(PxlStream_V_pixel_us_8_dout),
    .PxlStream_V_pixel_us_8_empty_n(PxlStream_V_pixel_us_8_empty_n),
    .PxlStream_V_pixel_us_8_read(Median_U0_PxlStream_V_pixel_us_8_read),
    .PxlStream_V_pixel_us_7_dout(PxlStream_V_pixel_us_7_dout),
    .PxlStream_V_pixel_us_7_empty_n(PxlStream_V_pixel_us_7_empty_n),
    .PxlStream_V_pixel_us_7_read(Median_U0_PxlStream_V_pixel_us_7_read),
    .PxlStream_V_pixel_us_6_dout(PxlStream_V_pixel_us_6_dout),
    .PxlStream_V_pixel_us_6_empty_n(PxlStream_V_pixel_us_6_empty_n),
    .PxlStream_V_pixel_us_6_read(Median_U0_PxlStream_V_pixel_us_6_read),
    .PxlStream_V_pixel_us_5_dout(PxlStream_V_pixel_us_5_dout),
    .PxlStream_V_pixel_us_5_empty_n(PxlStream_V_pixel_us_5_empty_n),
    .PxlStream_V_pixel_us_5_read(Median_U0_PxlStream_V_pixel_us_5_read),
    .PxlStream_V_pixel_us_4_dout(PxlStream_V_pixel_us_4_dout),
    .PxlStream_V_pixel_us_4_empty_n(PxlStream_V_pixel_us_4_empty_n),
    .PxlStream_V_pixel_us_4_read(Median_U0_PxlStream_V_pixel_us_4_read),
    .PxlStream_V_pixel_us_3_dout(PxlStream_V_pixel_us_3_dout),
    .PxlStream_V_pixel_us_3_empty_n(PxlStream_V_pixel_us_3_empty_n),
    .PxlStream_V_pixel_us_3_read(Median_U0_PxlStream_V_pixel_us_3_read),
    .PxlStream_V_pixel_us_2_dout(PxlStream_V_pixel_us_2_dout),
    .PxlStream_V_pixel_us_2_empty_n(PxlStream_V_pixel_us_2_empty_n),
    .PxlStream_V_pixel_us_2_read(Median_U0_PxlStream_V_pixel_us_2_read),
    .PxlStream_V_pixel_us_1_dout(PxlStream_V_pixel_us_1_dout),
    .PxlStream_V_pixel_us_1_empty_n(PxlStream_V_pixel_us_1_empty_n),
    .PxlStream_V_pixel_us_1_read(Median_U0_PxlStream_V_pixel_us_1_read),
    .PxlStream_V_pixel_us_dout(PxlStream_V_pixel_us_dout),
    .PxlStream_V_pixel_us_empty_n(PxlStream_V_pixel_us_empty_n),
    .PxlStream_V_pixel_us_read(Median_U0_PxlStream_V_pixel_us_read),
    .PxlStream_V_pixel_la_8_dout(PxlStream_V_pixel_la_8_dout),
    .PxlStream_V_pixel_la_8_empty_n(PxlStream_V_pixel_la_8_empty_n),
    .PxlStream_V_pixel_la_8_read(Median_U0_PxlStream_V_pixel_la_8_read),
    .PxlStream_V_pixel_la_7_dout(PxlStream_V_pixel_la_7_dout),
    .PxlStream_V_pixel_la_7_empty_n(PxlStream_V_pixel_la_7_empty_n),
    .PxlStream_V_pixel_la_7_read(Median_U0_PxlStream_V_pixel_la_7_read),
    .PxlStream_V_pixel_la_6_dout(PxlStream_V_pixel_la_6_dout),
    .PxlStream_V_pixel_la_6_empty_n(PxlStream_V_pixel_la_6_empty_n),
    .PxlStream_V_pixel_la_6_read(Median_U0_PxlStream_V_pixel_la_6_read),
    .PxlStream_V_pixel_la_5_dout(PxlStream_V_pixel_la_5_dout),
    .PxlStream_V_pixel_la_5_empty_n(PxlStream_V_pixel_la_5_empty_n),
    .PxlStream_V_pixel_la_5_read(Median_U0_PxlStream_V_pixel_la_5_read),
    .PxlStream_V_pixel_la_4_dout(PxlStream_V_pixel_la_4_dout),
    .PxlStream_V_pixel_la_4_empty_n(PxlStream_V_pixel_la_4_empty_n),
    .PxlStream_V_pixel_la_4_read(Median_U0_PxlStream_V_pixel_la_4_read),
    .PxlStream_V_pixel_la_3_dout(PxlStream_V_pixel_la_3_dout),
    .PxlStream_V_pixel_la_3_empty_n(PxlStream_V_pixel_la_3_empty_n),
    .PxlStream_V_pixel_la_3_read(Median_U0_PxlStream_V_pixel_la_3_read),
    .PxlStream_V_pixel_la_2_dout(PxlStream_V_pixel_la_2_dout),
    .PxlStream_V_pixel_la_2_empty_n(PxlStream_V_pixel_la_2_empty_n),
    .PxlStream_V_pixel_la_2_read(Median_U0_PxlStream_V_pixel_la_2_read),
    .PxlStream_V_pixel_la_1_dout(PxlStream_V_pixel_la_1_dout),
    .PxlStream_V_pixel_la_1_empty_n(PxlStream_V_pixel_la_1_empty_n),
    .PxlStream_V_pixel_la_1_read(Median_U0_PxlStream_V_pixel_la_1_read),
    .PxlStream_V_pixel_la_dout(PxlStream_V_pixel_la_dout),
    .PxlStream_V_pixel_la_empty_n(PxlStream_V_pixel_la_empty_n),
    .PxlStream_V_pixel_la_read(Median_U0_PxlStream_V_pixel_la_read),
    .MdnStream_V_data_V_din(Median_U0_MdnStream_V_data_V_din),
    .MdnStream_V_data_V_full_n(MdnStream_V_data_V_full_n),
    .MdnStream_V_data_V_write(Median_U0_MdnStream_V_data_V_write),
    .MdnStream_V_user_V_din(Median_U0_MdnStream_V_user_V_din),
    .MdnStream_V_user_V_full_n(MdnStream_V_user_V_full_n),
    .MdnStream_V_user_V_write(Median_U0_MdnStream_V_user_V_write),
    .MdnStream_V_last_V_din(Median_U0_MdnStream_V_last_V_din),
    .MdnStream_V_last_V_full_n(MdnStream_V_last_V_full_n),
    .MdnStream_V_last_V_write(Median_U0_MdnStream_V_last_V_write)
);

Color Color_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Color_U0_ap_start),
    .ap_done(Color_U0_ap_done),
    .ap_continue(Color_U0_ap_continue),
    .ap_idle(Color_U0_ap_idle),
    .ap_ready(Color_U0_ap_ready),
    .stream_out_TREADY(stream_out_TREADY),
    .stream_out_TDATA(Color_U0_stream_out_TDATA),
    .stream_out_TVALID(Color_U0_stream_out_TVALID),
    .stream_out_TUSER(Color_U0_stream_out_TUSER),
    .stream_out_TLAST(Color_U0_stream_out_TLAST),
    .MdnStream_V_data_V_dout(MdnStream_V_data_V_dout),
    .MdnStream_V_data_V_empty_n(MdnStream_V_data_V_empty_n),
    .MdnStream_V_data_V_read(Color_U0_MdnStream_V_data_V_read),
    .MdnStream_V_user_V_dout(MdnStream_V_user_V_dout),
    .MdnStream_V_user_V_empty_n(MdnStream_V_user_V_empty_n),
    .MdnStream_V_user_V_read(Color_U0_MdnStream_V_user_V_read),
    .MdnStream_V_last_V_dout(MdnStream_V_last_V_dout),
    .MdnStream_V_last_V_empty_n(MdnStream_V_last_V_empty_n),
    .MdnStream_V_last_V_read(Color_U0_MdnStream_V_last_V_read)
);

fifo_w8_d32_A BWStream_V_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(BlackWhite_U0_BWStream_V_data_V_din),
    .if_full_n(BWStream_V_data_V_full_n),
    .if_write(BlackWhite_U0_BWStream_V_data_V_write),
    .if_dout(BWStream_V_data_V_dout),
    .if_empty_n(BWStream_V_data_V_empty_n),
    .if_read(Matrix_U0_BWStream_V_data_V_read)
);

fifo_w1_d32_A BWStream_V_user_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(BlackWhite_U0_BWStream_V_user_V_din),
    .if_full_n(BWStream_V_user_V_full_n),
    .if_write(BlackWhite_U0_BWStream_V_user_V_write),
    .if_dout(BWStream_V_user_V_dout),
    .if_empty_n(BWStream_V_user_V_empty_n),
    .if_read(Matrix_U0_BWStream_V_user_V_read)
);

fifo_w1_d32_A BWStream_V_last_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(BlackWhite_U0_BWStream_V_last_V_din),
    .if_full_n(BWStream_V_last_V_full_n),
    .if_write(BlackWhite_U0_BWStream_V_last_V_write),
    .if_dout(BWStream_V_last_V_dout),
    .if_empty_n(BWStream_V_last_V_empty_n),
    .if_read(Matrix_U0_BWStream_V_last_V_read)
);

fifo_w8_d32_A PxlStream_V_pixel_da_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_da_8_din),
    .if_full_n(PxlStream_V_pixel_da_8_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_da_8_write),
    .if_dout(PxlStream_V_pixel_da_8_dout),
    .if_empty_n(PxlStream_V_pixel_da_8_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_da_8_read)
);

fifo_w8_d32_A PxlStream_V_pixel_da_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_da_7_din),
    .if_full_n(PxlStream_V_pixel_da_7_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_da_7_write),
    .if_dout(PxlStream_V_pixel_da_7_dout),
    .if_empty_n(PxlStream_V_pixel_da_7_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_da_7_read)
);

fifo_w8_d32_A PxlStream_V_pixel_da_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_da_6_din),
    .if_full_n(PxlStream_V_pixel_da_6_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_da_6_write),
    .if_dout(PxlStream_V_pixel_da_6_dout),
    .if_empty_n(PxlStream_V_pixel_da_6_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_da_6_read)
);

fifo_w8_d32_A PxlStream_V_pixel_da_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_da_5_din),
    .if_full_n(PxlStream_V_pixel_da_5_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_da_5_write),
    .if_dout(PxlStream_V_pixel_da_5_dout),
    .if_empty_n(PxlStream_V_pixel_da_5_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_da_5_read)
);

fifo_w8_d32_A PxlStream_V_pixel_da_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_da_4_din),
    .if_full_n(PxlStream_V_pixel_da_4_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_da_4_write),
    .if_dout(PxlStream_V_pixel_da_4_dout),
    .if_empty_n(PxlStream_V_pixel_da_4_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_da_4_read)
);

fifo_w8_d32_A PxlStream_V_pixel_da_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_da_3_din),
    .if_full_n(PxlStream_V_pixel_da_3_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_da_3_write),
    .if_dout(PxlStream_V_pixel_da_3_dout),
    .if_empty_n(PxlStream_V_pixel_da_3_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_da_3_read)
);

fifo_w8_d32_A PxlStream_V_pixel_da_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_da_2_din),
    .if_full_n(PxlStream_V_pixel_da_2_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_da_2_write),
    .if_dout(PxlStream_V_pixel_da_2_dout),
    .if_empty_n(PxlStream_V_pixel_da_2_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_da_2_read)
);

fifo_w8_d32_A PxlStream_V_pixel_da_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_da_1_din),
    .if_full_n(PxlStream_V_pixel_da_1_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_da_1_write),
    .if_dout(PxlStream_V_pixel_da_1_dout),
    .if_empty_n(PxlStream_V_pixel_da_1_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_da_1_read)
);

fifo_w8_d32_A PxlStream_V_pixel_da_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_da_din),
    .if_full_n(PxlStream_V_pixel_da_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_da_write),
    .if_dout(PxlStream_V_pixel_da_dout),
    .if_empty_n(PxlStream_V_pixel_da_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_da_read)
);

fifo_w1_d32_A PxlStream_V_pixel_us_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_us_8_din),
    .if_full_n(PxlStream_V_pixel_us_8_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_us_8_write),
    .if_dout(PxlStream_V_pixel_us_8_dout),
    .if_empty_n(PxlStream_V_pixel_us_8_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_us_8_read)
);

fifo_w1_d32_A PxlStream_V_pixel_us_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_us_7_din),
    .if_full_n(PxlStream_V_pixel_us_7_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_us_7_write),
    .if_dout(PxlStream_V_pixel_us_7_dout),
    .if_empty_n(PxlStream_V_pixel_us_7_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_us_7_read)
);

fifo_w1_d32_A PxlStream_V_pixel_us_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_us_6_din),
    .if_full_n(PxlStream_V_pixel_us_6_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_us_6_write),
    .if_dout(PxlStream_V_pixel_us_6_dout),
    .if_empty_n(PxlStream_V_pixel_us_6_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_us_6_read)
);

fifo_w1_d32_A PxlStream_V_pixel_us_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_us_5_din),
    .if_full_n(PxlStream_V_pixel_us_5_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_us_5_write),
    .if_dout(PxlStream_V_pixel_us_5_dout),
    .if_empty_n(PxlStream_V_pixel_us_5_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_us_5_read)
);

fifo_w1_d32_A PxlStream_V_pixel_us_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_us_4_din),
    .if_full_n(PxlStream_V_pixel_us_4_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_us_4_write),
    .if_dout(PxlStream_V_pixel_us_4_dout),
    .if_empty_n(PxlStream_V_pixel_us_4_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_us_4_read)
);

fifo_w1_d32_A PxlStream_V_pixel_us_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_us_3_din),
    .if_full_n(PxlStream_V_pixel_us_3_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_us_3_write),
    .if_dout(PxlStream_V_pixel_us_3_dout),
    .if_empty_n(PxlStream_V_pixel_us_3_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_us_3_read)
);

fifo_w1_d32_A PxlStream_V_pixel_us_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_us_2_din),
    .if_full_n(PxlStream_V_pixel_us_2_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_us_2_write),
    .if_dout(PxlStream_V_pixel_us_2_dout),
    .if_empty_n(PxlStream_V_pixel_us_2_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_us_2_read)
);

fifo_w1_d32_A PxlStream_V_pixel_us_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_us_1_din),
    .if_full_n(PxlStream_V_pixel_us_1_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_us_1_write),
    .if_dout(PxlStream_V_pixel_us_1_dout),
    .if_empty_n(PxlStream_V_pixel_us_1_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_us_1_read)
);

fifo_w1_d32_A PxlStream_V_pixel_us_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_us_din),
    .if_full_n(PxlStream_V_pixel_us_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_us_write),
    .if_dout(PxlStream_V_pixel_us_dout),
    .if_empty_n(PxlStream_V_pixel_us_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_us_read)
);

fifo_w1_d32_A PxlStream_V_pixel_la_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_la_8_din),
    .if_full_n(PxlStream_V_pixel_la_8_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_la_8_write),
    .if_dout(PxlStream_V_pixel_la_8_dout),
    .if_empty_n(PxlStream_V_pixel_la_8_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_la_8_read)
);

fifo_w1_d32_A PxlStream_V_pixel_la_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_la_7_din),
    .if_full_n(PxlStream_V_pixel_la_7_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_la_7_write),
    .if_dout(PxlStream_V_pixel_la_7_dout),
    .if_empty_n(PxlStream_V_pixel_la_7_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_la_7_read)
);

fifo_w1_d32_A PxlStream_V_pixel_la_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_la_6_din),
    .if_full_n(PxlStream_V_pixel_la_6_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_la_6_write),
    .if_dout(PxlStream_V_pixel_la_6_dout),
    .if_empty_n(PxlStream_V_pixel_la_6_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_la_6_read)
);

fifo_w1_d32_A PxlStream_V_pixel_la_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_la_5_din),
    .if_full_n(PxlStream_V_pixel_la_5_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_la_5_write),
    .if_dout(PxlStream_V_pixel_la_5_dout),
    .if_empty_n(PxlStream_V_pixel_la_5_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_la_5_read)
);

fifo_w1_d32_A PxlStream_V_pixel_la_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_la_4_din),
    .if_full_n(PxlStream_V_pixel_la_4_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_la_4_write),
    .if_dout(PxlStream_V_pixel_la_4_dout),
    .if_empty_n(PxlStream_V_pixel_la_4_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_la_4_read)
);

fifo_w1_d32_A PxlStream_V_pixel_la_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_la_3_din),
    .if_full_n(PxlStream_V_pixel_la_3_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_la_3_write),
    .if_dout(PxlStream_V_pixel_la_3_dout),
    .if_empty_n(PxlStream_V_pixel_la_3_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_la_3_read)
);

fifo_w1_d32_A PxlStream_V_pixel_la_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_la_2_din),
    .if_full_n(PxlStream_V_pixel_la_2_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_la_2_write),
    .if_dout(PxlStream_V_pixel_la_2_dout),
    .if_empty_n(PxlStream_V_pixel_la_2_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_la_2_read)
);

fifo_w1_d32_A PxlStream_V_pixel_la_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_la_1_din),
    .if_full_n(PxlStream_V_pixel_la_1_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_la_1_write),
    .if_dout(PxlStream_V_pixel_la_1_dout),
    .if_empty_n(PxlStream_V_pixel_la_1_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_la_1_read)
);

fifo_w1_d32_A PxlStream_V_pixel_la_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Matrix_U0_PxlStream_V_pixel_la_din),
    .if_full_n(PxlStream_V_pixel_la_full_n),
    .if_write(Matrix_U0_PxlStream_V_pixel_la_write),
    .if_dout(PxlStream_V_pixel_la_dout),
    .if_empty_n(PxlStream_V_pixel_la_empty_n),
    .if_read(Median_U0_PxlStream_V_pixel_la_read)
);

fifo_w8_d32_A MdnStream_V_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Median_U0_MdnStream_V_data_V_din),
    .if_full_n(MdnStream_V_data_V_full_n),
    .if_write(Median_U0_MdnStream_V_data_V_write),
    .if_dout(MdnStream_V_data_V_dout),
    .if_empty_n(MdnStream_V_data_V_empty_n),
    .if_read(Color_U0_MdnStream_V_data_V_read)
);

fifo_w1_d32_A MdnStream_V_user_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Median_U0_MdnStream_V_user_V_din),
    .if_full_n(MdnStream_V_user_V_full_n),
    .if_write(Median_U0_MdnStream_V_user_V_write),
    .if_dout(MdnStream_V_user_V_dout),
    .if_empty_n(MdnStream_V_user_V_empty_n),
    .if_read(Color_U0_MdnStream_V_user_V_read)
);

fifo_w1_d32_A MdnStream_V_last_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Median_U0_MdnStream_V_last_V_din),
    .if_full_n(MdnStream_V_last_V_full_n),
    .if_write(Median_U0_MdnStream_V_last_V_write),
    .if_dout(MdnStream_V_last_V_dout),
    .if_empty_n(MdnStream_V_last_V_empty_n),
    .if_read(Color_U0_MdnStream_V_last_V_read)
);

start_for_Matrix_U0 start_for_Matrix_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Matrix_U0_din),
    .if_full_n(start_for_Matrix_U0_full_n),
    .if_write(BlackWhite_U0_start_write),
    .if_dout(start_for_Matrix_U0_dout),
    .if_empty_n(start_for_Matrix_U0_empty_n),
    .if_read(Matrix_U0_ap_ready)
);

start_for_Median_U0 start_for_Median_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Median_U0_din),
    .if_full_n(start_for_Median_U0_full_n),
    .if_write(Matrix_U0_start_write),
    .if_dout(start_for_Median_U0_dout),
    .if_empty_n(start_for_Median_U0_empty_n),
    .if_read(Median_U0_ap_ready)
);

start_for_Color_U0 start_for_Color_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Color_U0_din),
    .if_full_n(start_for_Color_U0_full_n),
    .if_write(Median_U0_start_write),
    .if_dout(start_for_Color_U0_dout),
    .if_empty_n(start_for_Color_U0_empty_n),
    .if_read(Color_U0_ap_ready)
);

assign BlackWhite_U0_ap_continue = 1'b1;

assign BlackWhite_U0_ap_start = 1'b1;

assign BlackWhite_U0_start_full_n = (start_for_Matrix_U0_full_n | 1'b0);

assign Color_U0_ap_continue = 1'b1;

assign Color_U0_ap_start = start_for_Color_U0_empty_n;

assign Color_U0_start_full_n = 1'b0;

assign Color_U0_start_write = 1'b0;

assign Matrix_U0_ap_continue = 1'b1;

assign Matrix_U0_ap_start = start_for_Matrix_U0_empty_n;

assign Matrix_U0_start_full_n = (1'b0 | start_for_Median_U0_full_n);

assign Median_U0_ap_continue = 1'b1;

assign Median_U0_ap_start = start_for_Median_U0_empty_n;

assign Median_U0_start_full_n = (1'b0 | start_for_Color_U0_full_n);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b0;

assign start_for_Color_U0_din = 1'b1;

assign start_for_Matrix_U0_din = 1'b1;

assign start_for_Median_U0_din = 1'b1;

assign stream_in_TREADY = BlackWhite_U0_stream_in_TREADY;

assign stream_out_TDATA = Color_U0_stream_out_TDATA;

assign stream_out_TLAST = Color_U0_stream_out_TLAST;

assign stream_out_TUSER = Color_U0_stream_out_TUSER;

assign stream_out_TVALID = Color_U0_stream_out_TVALID;

endmodule //top
