-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.2
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Median is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    PxlStream_V_pixel_da_8_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    PxlStream_V_pixel_da_8_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_da_8_read : OUT STD_LOGIC;
    PxlStream_V_pixel_da_7_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    PxlStream_V_pixel_da_7_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_da_7_read : OUT STD_LOGIC;
    PxlStream_V_pixel_da_6_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    PxlStream_V_pixel_da_6_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_da_6_read : OUT STD_LOGIC;
    PxlStream_V_pixel_da_5_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    PxlStream_V_pixel_da_5_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_da_5_read : OUT STD_LOGIC;
    PxlStream_V_pixel_da_4_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    PxlStream_V_pixel_da_4_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_da_4_read : OUT STD_LOGIC;
    PxlStream_V_pixel_da_3_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    PxlStream_V_pixel_da_3_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_da_3_read : OUT STD_LOGIC;
    PxlStream_V_pixel_da_2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    PxlStream_V_pixel_da_2_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_da_2_read : OUT STD_LOGIC;
    PxlStream_V_pixel_da_1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    PxlStream_V_pixel_da_1_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_da_1_read : OUT STD_LOGIC;
    PxlStream_V_pixel_da_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    PxlStream_V_pixel_da_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_da_read : OUT STD_LOGIC;
    PxlStream_V_pixel_us_8_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_us_8_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_us_8_read : OUT STD_LOGIC;
    PxlStream_V_pixel_us_7_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_us_7_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_us_7_read : OUT STD_LOGIC;
    PxlStream_V_pixel_us_6_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_us_6_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_us_6_read : OUT STD_LOGIC;
    PxlStream_V_pixel_us_5_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_us_5_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_us_5_read : OUT STD_LOGIC;
    PxlStream_V_pixel_us_4_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_us_4_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_us_4_read : OUT STD_LOGIC;
    PxlStream_V_pixel_us_3_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_us_3_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_us_3_read : OUT STD_LOGIC;
    PxlStream_V_pixel_us_2_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_us_2_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_us_2_read : OUT STD_LOGIC;
    PxlStream_V_pixel_us_1_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_us_1_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_us_1_read : OUT STD_LOGIC;
    PxlStream_V_pixel_us_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_us_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_us_read : OUT STD_LOGIC;
    PxlStream_V_pixel_la_8_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_la_8_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_la_8_read : OUT STD_LOGIC;
    PxlStream_V_pixel_la_7_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_la_7_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_la_7_read : OUT STD_LOGIC;
    PxlStream_V_pixel_la_6_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_la_6_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_la_6_read : OUT STD_LOGIC;
    PxlStream_V_pixel_la_5_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_la_5_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_la_5_read : OUT STD_LOGIC;
    PxlStream_V_pixel_la_4_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_la_4_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_la_4_read : OUT STD_LOGIC;
    PxlStream_V_pixel_la_3_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_la_3_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_la_3_read : OUT STD_LOGIC;
    PxlStream_V_pixel_la_2_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_la_2_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_la_2_read : OUT STD_LOGIC;
    PxlStream_V_pixel_la_1_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_la_1_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_la_1_read : OUT STD_LOGIC;
    PxlStream_V_pixel_la_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    PxlStream_V_pixel_la_empty_n : IN STD_LOGIC;
    PxlStream_V_pixel_la_read : OUT STD_LOGIC;
    MdnStream_V_data_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    MdnStream_V_data_V_full_n : IN STD_LOGIC;
    MdnStream_V_data_V_write : OUT STD_LOGIC;
    MdnStream_V_user_V_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    MdnStream_V_user_V_full_n : IN STD_LOGIC;
    MdnStream_V_user_V_write : OUT STD_LOGIC;
    MdnStream_V_last_V_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    MdnStream_V_last_V_full_n : IN STD_LOGIC;
    MdnStream_V_last_V_write : OUT STD_LOGIC );
end;


architecture behav of Median is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal real_start : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal MdnStream_V_data_V1_status : STD_LOGIC;
    signal empty_n_1_reg_825 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter12_empty_n_1_reg_825 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_pp0_stage0_flag00011001 : BOOLEAN;
    signal start_once_reg : STD_LOGIC := '0';
    signal MdnStream_V_data_V_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_flag00000000 : BOOLEAN;
    signal MdnStream_V_user_V_blk_n : STD_LOGIC;
    signal MdnStream_V_last_V_blk_n : STD_LOGIC;
    signal ap_reg_pp0_iter1_empty_n_1_reg_825 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter2_empty_n_1_reg_825 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter3_empty_n_1_reg_825 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter4_empty_n_1_reg_825 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter5_empty_n_1_reg_825 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter6_empty_n_1_reg_825 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter7_empty_n_1_reg_825 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter8_empty_n_1_reg_825 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter9_empty_n_1_reg_825 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter10_empty_n_1_reg_825 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter11_empty_n_1_reg_825 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_pixel_data_V_0_0_reg_829 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_pixel_data_V_0_1_reg_836 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_pixel_data_V_0_2_reg_843 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_pixel_data_V_1_0_reg_850 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_pixel_data_V_1_1_reg_857 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_pixel_data_V_1_2_reg_864 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_pixel_data_V_2_0_reg_871 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_pixel_data_V_2_1_reg_878 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_pixel_data_V_2_2_reg_885 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_pp0_iter1_tmp_pixel_data_V_2_2_reg_885 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_user_V_reg_892 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter1_tmp_user_V_reg_892 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter2_tmp_user_V_reg_892 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter3_tmp_user_V_reg_892 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter4_tmp_user_V_reg_892 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter5_tmp_user_V_reg_892 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter6_tmp_user_V_reg_892 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter7_tmp_user_V_reg_892 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter8_tmp_user_V_reg_892 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter9_tmp_user_V_reg_892 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter10_tmp_user_V_reg_892 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter11_tmp_user_V_reg_892 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter12_tmp_user_V_reg_892 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_897 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter1_tmp_last_V_reg_897 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter2_tmp_last_V_reg_897 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter3_tmp_last_V_reg_897 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter4_tmp_last_V_reg_897 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter5_tmp_last_V_reg_897 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter6_tmp_last_V_reg_897 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter7_tmp_last_V_reg_897 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter8_tmp_last_V_reg_897 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter9_tmp_last_V_reg_897 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter10_tmp_last_V_reg_897 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter11_tmp_last_V_reg_897 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter12_tmp_last_V_reg_897 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge_i_fu_205_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge_i_reg_902 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_i_fu_211_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_i_reg_909 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_pp0_iter2_buffer_V_load_i_reg_909 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge1_i_fu_221_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge1_i_reg_916 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_i_fu_227_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_i_reg_923 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge2_i_fu_237_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge2_i_reg_930 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_i_fu_243_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_i_reg_937 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge3_i_fu_253_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge3_i_reg_944 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_i_fu_259_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_i_reg_951 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge4_i_fu_269_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge4_i_reg_958 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge5_i_fu_275_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge5_i_reg_965 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge6_i_fu_285_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge6_i_reg_972 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge7_i_fu_291_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge7_i_reg_979 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge8_i_fu_301_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge8_i_reg_986 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge9_i_fu_307_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge9_i_reg_993 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_8_i_fu_317_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_8_i_reg_1000 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_9_i_fu_323_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_9_i_reg_1007 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_pp0_iter3_buffer_V_load_9_i_reg_1007 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge10_i_fu_333_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge10_i_reg_1014 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_pp0_iter4_storemerge10_i_reg_1014 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_11_i_fu_339_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_11_i_reg_1021 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge11_i_fu_349_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge11_i_reg_1028 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_13_i_fu_355_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_13_i_reg_1035 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge12_i_fu_365_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge12_i_reg_1042 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_15_i_fu_371_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_15_i_reg_1049 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge13_i_fu_381_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge13_i_reg_1056 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_17_i_fu_387_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_17_i_reg_1063 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge14_i_fu_397_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge14_i_reg_1070 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_3_1_i_fu_403_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_3_1_i_reg_1077 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge15_i_fu_413_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge15_i_reg_1084 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_5_1_i_fu_419_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_5_1_i_reg_1091 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge16_i_fu_429_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge16_i_reg_1098 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_7_1_i_fu_435_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_7_1_i_reg_1105 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge17_i_fu_445_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge17_i_reg_1112 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_9_1_i_fu_451_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_9_1_i_reg_1119 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_pp0_iter5_buffer_V_load_9_1_i_reg_1119 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge18_i_fu_461_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge18_i_reg_1126 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_pp0_iter6_storemerge18_i_reg_1126 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_11_1_i_fu_467_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_11_1_i_reg_1133 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge19_i_fu_477_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge19_i_reg_1140 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_13_1_i_fu_483_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_13_1_i_reg_1147 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge20_i_fu_493_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge20_i_reg_1154 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_15_1_i_fu_499_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_15_1_i_reg_1161 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge21_i_fu_509_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge21_i_reg_1168 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_17_1_i_fu_515_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_17_1_i_reg_1175 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge22_i_fu_525_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge22_i_reg_1182 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_3_2_i_fu_531_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_3_2_i_reg_1189 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge23_i_fu_541_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge23_i_reg_1196 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_5_2_i_fu_547_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_5_2_i_reg_1203 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge24_i_fu_557_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge24_i_reg_1210 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_7_2_i_fu_563_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_7_2_i_reg_1217 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge25_i_fu_573_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge25_i_reg_1224 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_9_2_i_fu_579_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_9_2_i_reg_1231 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_pp0_iter7_buffer_V_load_9_2_i_reg_1231 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge26_i_fu_589_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge26_i_reg_1237 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_pp0_iter8_storemerge26_i_reg_1237 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_11_2_i_fu_595_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_11_2_i_reg_1243 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge27_i_fu_605_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge27_i_reg_1250 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_13_2_i_fu_611_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_13_2_i_reg_1257 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge28_i_fu_621_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge28_i_reg_1264 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_15_2_i_fu_627_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_15_2_i_reg_1271 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge29_i_fu_637_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge29_i_reg_1278 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_17_2_i_fu_643_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_17_2_i_reg_1285 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge30_i_fu_653_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge30_i_reg_1291 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_3_3_i_fu_659_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_3_3_i_reg_1297 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge31_i_fu_669_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge31_i_reg_1304 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_5_3_i_fu_675_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_5_3_i_reg_1311 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge32_i_fu_685_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge32_i_reg_1318 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_7_3_i_fu_691_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_7_3_i_reg_1325 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge33_i_fu_701_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge33_i_reg_1331 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_11_3_i_fu_711_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_11_3_i_reg_1337 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge34_i_fu_721_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge34_i_reg_1343 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_13_3_i_fu_727_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_13_3_i_reg_1349 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge35_i_fu_737_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge35_i_reg_1356 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_15_3_i_fu_743_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_15_3_i_reg_1363 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge36_i_fu_753_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge36_i_reg_1369 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_3_4_i_fu_763_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_3_4_i_reg_1375 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge37_i_fu_773_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge37_i_reg_1381 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_5_4_i_fu_779_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_5_4_i_reg_1387 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge38_i_fu_789_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge38_i_reg_1393 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_13_4_i_fu_799_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_V_load_13_4_i_reg_1399 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge39_i_fu_809_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge39_i_reg_1405 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_data_V_fu_819_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_data_V_reg_1411 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_flag00011011 : BOOLEAN;
    signal PxlStream_V_pixel_da0_update : STD_LOGIC;
    signal ap_condition_502 : BOOLEAN;
    signal empty_n_nbread_fu_82_p28_0 : STD_LOGIC_VECTOR (0 downto 0);
    signal MdnStream_V_data_V1_update : STD_LOGIC;
    signal ap_block_pp0_stage0_flag00001001 : BOOLEAN;
    signal tmp_2_i_fu_201_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_i_fu_217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_i_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_i_fu_249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_i_fu_265_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_i_fu_281_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_i_fu_297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_i_fu_313_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_i_fu_329_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_i_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_i_fu_361_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_i_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_i_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_i_fu_409_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_i_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_i_fu_441_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_1_i_fu_457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_1_i_fu_473_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_1_i_fu_489_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_1_i_fu_505_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_1_i_fu_521_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_1_i_fu_537_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_1_i_fu_553_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_1_i_fu_569_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_2_i_fu_585_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_2_i_fu_601_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_2_i_fu_617_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_2_i_fu_633_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_2_i_fu_649_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_2_i_fu_665_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_2_i_fu_681_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_2_i_fu_697_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_3_i_fu_707_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_3_i_fu_717_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_3_i_fu_733_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_3_i_fu_749_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_3_i_fu_759_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_3_i_fu_769_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_3_i_fu_785_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_4_i_fu_795_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_4_i_fu_805_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_4_i_fu_815_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to12 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_enable_reg_pp0_iter13) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0))) then 
                    ap_enable_reg_pp0_iter1 <= real_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = real_start)) then 
                    start_once_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0)) then
                ap_reg_pp0_iter10_empty_n_1_reg_825 <= ap_reg_pp0_iter9_empty_n_1_reg_825;
                ap_reg_pp0_iter10_tmp_last_V_reg_897 <= ap_reg_pp0_iter9_tmp_last_V_reg_897;
                ap_reg_pp0_iter10_tmp_user_V_reg_892 <= ap_reg_pp0_iter9_tmp_user_V_reg_892;
                ap_reg_pp0_iter11_empty_n_1_reg_825 <= ap_reg_pp0_iter10_empty_n_1_reg_825;
                ap_reg_pp0_iter11_tmp_last_V_reg_897 <= ap_reg_pp0_iter10_tmp_last_V_reg_897;
                ap_reg_pp0_iter11_tmp_user_V_reg_892 <= ap_reg_pp0_iter10_tmp_user_V_reg_892;
                ap_reg_pp0_iter12_empty_n_1_reg_825 <= ap_reg_pp0_iter11_empty_n_1_reg_825;
                ap_reg_pp0_iter12_tmp_last_V_reg_897 <= ap_reg_pp0_iter11_tmp_last_V_reg_897;
                ap_reg_pp0_iter12_tmp_user_V_reg_892 <= ap_reg_pp0_iter11_tmp_user_V_reg_892;
                ap_reg_pp0_iter2_buffer_V_load_i_reg_909 <= buffer_V_load_i_reg_909;
                ap_reg_pp0_iter2_empty_n_1_reg_825 <= ap_reg_pp0_iter1_empty_n_1_reg_825;
                ap_reg_pp0_iter2_tmp_last_V_reg_897 <= ap_reg_pp0_iter1_tmp_last_V_reg_897;
                ap_reg_pp0_iter2_tmp_user_V_reg_892 <= ap_reg_pp0_iter1_tmp_user_V_reg_892;
                ap_reg_pp0_iter3_buffer_V_load_9_i_reg_1007 <= buffer_V_load_9_i_reg_1007;
                ap_reg_pp0_iter3_empty_n_1_reg_825 <= ap_reg_pp0_iter2_empty_n_1_reg_825;
                ap_reg_pp0_iter3_tmp_last_V_reg_897 <= ap_reg_pp0_iter2_tmp_last_V_reg_897;
                ap_reg_pp0_iter3_tmp_user_V_reg_892 <= ap_reg_pp0_iter2_tmp_user_V_reg_892;
                ap_reg_pp0_iter4_empty_n_1_reg_825 <= ap_reg_pp0_iter3_empty_n_1_reg_825;
                ap_reg_pp0_iter4_storemerge10_i_reg_1014 <= storemerge10_i_reg_1014;
                ap_reg_pp0_iter4_tmp_last_V_reg_897 <= ap_reg_pp0_iter3_tmp_last_V_reg_897;
                ap_reg_pp0_iter4_tmp_user_V_reg_892 <= ap_reg_pp0_iter3_tmp_user_V_reg_892;
                ap_reg_pp0_iter5_buffer_V_load_9_1_i_reg_1119 <= buffer_V_load_9_1_i_reg_1119;
                ap_reg_pp0_iter5_empty_n_1_reg_825 <= ap_reg_pp0_iter4_empty_n_1_reg_825;
                ap_reg_pp0_iter5_tmp_last_V_reg_897 <= ap_reg_pp0_iter4_tmp_last_V_reg_897;
                ap_reg_pp0_iter5_tmp_user_V_reg_892 <= ap_reg_pp0_iter4_tmp_user_V_reg_892;
                ap_reg_pp0_iter6_empty_n_1_reg_825 <= ap_reg_pp0_iter5_empty_n_1_reg_825;
                ap_reg_pp0_iter6_storemerge18_i_reg_1126 <= storemerge18_i_reg_1126;
                ap_reg_pp0_iter6_tmp_last_V_reg_897 <= ap_reg_pp0_iter5_tmp_last_V_reg_897;
                ap_reg_pp0_iter6_tmp_user_V_reg_892 <= ap_reg_pp0_iter5_tmp_user_V_reg_892;
                ap_reg_pp0_iter7_buffer_V_load_9_2_i_reg_1231 <= buffer_V_load_9_2_i_reg_1231;
                ap_reg_pp0_iter7_empty_n_1_reg_825 <= ap_reg_pp0_iter6_empty_n_1_reg_825;
                ap_reg_pp0_iter7_tmp_last_V_reg_897 <= ap_reg_pp0_iter6_tmp_last_V_reg_897;
                ap_reg_pp0_iter7_tmp_user_V_reg_892 <= ap_reg_pp0_iter6_tmp_user_V_reg_892;
                ap_reg_pp0_iter8_empty_n_1_reg_825 <= ap_reg_pp0_iter7_empty_n_1_reg_825;
                ap_reg_pp0_iter8_storemerge26_i_reg_1237 <= storemerge26_i_reg_1237;
                ap_reg_pp0_iter8_tmp_last_V_reg_897 <= ap_reg_pp0_iter7_tmp_last_V_reg_897;
                ap_reg_pp0_iter8_tmp_user_V_reg_892 <= ap_reg_pp0_iter7_tmp_user_V_reg_892;
                ap_reg_pp0_iter9_empty_n_1_reg_825 <= ap_reg_pp0_iter8_empty_n_1_reg_825;
                ap_reg_pp0_iter9_tmp_last_V_reg_897 <= ap_reg_pp0_iter8_tmp_last_V_reg_897;
                ap_reg_pp0_iter9_tmp_user_V_reg_892 <= ap_reg_pp0_iter8_tmp_user_V_reg_892;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then
                ap_reg_pp0_iter1_empty_n_1_reg_825 <= empty_n_1_reg_825;
                ap_reg_pp0_iter1_tmp_last_V_reg_897 <= tmp_last_V_reg_897;
                ap_reg_pp0_iter1_tmp_pixel_data_V_2_2_reg_885 <= tmp_pixel_data_V_2_2_reg_885;
                ap_reg_pp0_iter1_tmp_user_V_reg_892 <= tmp_user_V_reg_892;
                empty_n_1_reg_825 <= empty_n_nbread_fu_82_p28_0;
                tmp_last_V_reg_897 <= PxlStream_V_pixel_la_4_dout;
                tmp_pixel_data_V_0_0_reg_829 <= PxlStream_V_pixel_da_8_dout;
                tmp_pixel_data_V_0_1_reg_836 <= PxlStream_V_pixel_da_7_dout;
                tmp_pixel_data_V_0_2_reg_843 <= PxlStream_V_pixel_da_6_dout;
                tmp_pixel_data_V_1_0_reg_850 <= PxlStream_V_pixel_da_5_dout;
                tmp_pixel_data_V_1_1_reg_857 <= PxlStream_V_pixel_da_4_dout;
                tmp_pixel_data_V_1_2_reg_864 <= PxlStream_V_pixel_da_3_dout;
                tmp_pixel_data_V_2_0_reg_871 <= PxlStream_V_pixel_da_2_dout;
                tmp_pixel_data_V_2_1_reg_878 <= PxlStream_V_pixel_da_1_dout;
                tmp_pixel_data_V_2_2_reg_885 <= PxlStream_V_pixel_da_dout;
                tmp_user_V_reg_892 <= PxlStream_V_pixel_us_4_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_1 = ap_reg_pp0_iter4_empty_n_1_reg_825))) then
                buffer_V_load_11_1_i_reg_1133 <= buffer_V_load_11_1_i_fu_467_p3;
                buffer_V_load_13_1_i_reg_1147 <= buffer_V_load_13_1_i_fu_483_p3;
                buffer_V_load_15_1_i_reg_1161 <= buffer_V_load_15_1_i_fu_499_p3;
                buffer_V_load_17_1_i_reg_1175 <= buffer_V_load_17_1_i_fu_515_p3;
                storemerge18_i_reg_1126 <= storemerge18_i_fu_461_p3;
                storemerge19_i_reg_1140 <= storemerge19_i_fu_477_p3;
                storemerge20_i_reg_1154 <= storemerge20_i_fu_493_p3;
                storemerge21_i_reg_1168 <= storemerge21_i_fu_509_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_1 = ap_reg_pp0_iter6_empty_n_1_reg_825))) then
                buffer_V_load_11_2_i_reg_1243 <= buffer_V_load_11_2_i_fu_595_p3;
                buffer_V_load_13_2_i_reg_1257 <= buffer_V_load_13_2_i_fu_611_p3;
                buffer_V_load_15_2_i_reg_1271 <= buffer_V_load_15_2_i_fu_627_p3;
                buffer_V_load_17_2_i_reg_1285 <= buffer_V_load_17_2_i_fu_643_p3;
                storemerge26_i_reg_1237 <= storemerge26_i_fu_589_p3;
                storemerge27_i_reg_1250 <= storemerge27_i_fu_605_p3;
                storemerge28_i_reg_1264 <= storemerge28_i_fu_621_p3;
                storemerge29_i_reg_1278 <= storemerge29_i_fu_637_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_1 = ap_reg_pp0_iter8_empty_n_1_reg_825))) then
                buffer_V_load_11_3_i_reg_1337 <= buffer_V_load_11_3_i_fu_711_p3;
                buffer_V_load_13_3_i_reg_1349 <= buffer_V_load_13_3_i_fu_727_p3;
                buffer_V_load_15_3_i_reg_1363 <= buffer_V_load_15_3_i_fu_743_p3;
                storemerge34_i_reg_1343 <= storemerge34_i_fu_721_p3;
                storemerge35_i_reg_1356 <= storemerge35_i_fu_737_p3;
                storemerge36_i_reg_1369 <= storemerge36_i_fu_753_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_1 = ap_reg_pp0_iter2_empty_n_1_reg_825))) then
                buffer_V_load_11_i_reg_1021 <= buffer_V_load_11_i_fu_339_p3;
                buffer_V_load_13_i_reg_1035 <= buffer_V_load_13_i_fu_355_p3;
                buffer_V_load_15_i_reg_1049 <= buffer_V_load_15_i_fu_371_p3;
                buffer_V_load_17_i_reg_1063 <= buffer_V_load_17_i_fu_387_p3;
                storemerge10_i_reg_1014 <= storemerge10_i_fu_333_p3;
                storemerge11_i_reg_1028 <= storemerge11_i_fu_349_p3;
                storemerge12_i_reg_1042 <= storemerge12_i_fu_365_p3;
                storemerge13_i_reg_1056 <= storemerge13_i_fu_381_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_1 = ap_reg_pp0_iter10_empty_n_1_reg_825))) then
                buffer_V_load_13_4_i_reg_1399 <= buffer_V_load_13_4_i_fu_799_p3;
                storemerge39_i_reg_1405 <= storemerge39_i_fu_809_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_1 = ap_reg_pp0_iter3_empty_n_1_reg_825))) then
                buffer_V_load_3_1_i_reg_1077 <= buffer_V_load_3_1_i_fu_403_p3;
                buffer_V_load_5_1_i_reg_1091 <= buffer_V_load_5_1_i_fu_419_p3;
                buffer_V_load_7_1_i_reg_1105 <= buffer_V_load_7_1_i_fu_435_p3;
                buffer_V_load_9_1_i_reg_1119 <= buffer_V_load_9_1_i_fu_451_p3;
                storemerge14_i_reg_1070 <= storemerge14_i_fu_397_p3;
                storemerge15_i_reg_1084 <= storemerge15_i_fu_413_p3;
                storemerge16_i_reg_1098 <= storemerge16_i_fu_429_p3;
                storemerge17_i_reg_1112 <= storemerge17_i_fu_445_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_1 = ap_reg_pp0_iter5_empty_n_1_reg_825))) then
                buffer_V_load_3_2_i_reg_1189 <= buffer_V_load_3_2_i_fu_531_p3;
                buffer_V_load_5_2_i_reg_1203 <= buffer_V_load_5_2_i_fu_547_p3;
                buffer_V_load_7_2_i_reg_1217 <= buffer_V_load_7_2_i_fu_563_p3;
                buffer_V_load_9_2_i_reg_1231 <= buffer_V_load_9_2_i_fu_579_p3;
                storemerge22_i_reg_1182 <= storemerge22_i_fu_525_p3;
                storemerge23_i_reg_1196 <= storemerge23_i_fu_541_p3;
                storemerge24_i_reg_1210 <= storemerge24_i_fu_557_p3;
                storemerge25_i_reg_1224 <= storemerge25_i_fu_573_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_1 = ap_reg_pp0_iter7_empty_n_1_reg_825))) then
                buffer_V_load_3_3_i_reg_1297 <= buffer_V_load_3_3_i_fu_659_p3;
                buffer_V_load_5_3_i_reg_1311 <= buffer_V_load_5_3_i_fu_675_p3;
                buffer_V_load_7_3_i_reg_1325 <= buffer_V_load_7_3_i_fu_691_p3;
                storemerge30_i_reg_1291 <= storemerge30_i_fu_653_p3;
                storemerge31_i_reg_1304 <= storemerge31_i_fu_669_p3;
                storemerge32_i_reg_1318 <= storemerge32_i_fu_685_p3;
                storemerge33_i_reg_1331 <= storemerge33_i_fu_701_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_1 = ap_reg_pp0_iter9_empty_n_1_reg_825))) then
                buffer_V_load_3_4_i_reg_1375 <= buffer_V_load_3_4_i_fu_763_p3;
                buffer_V_load_5_4_i_reg_1387 <= buffer_V_load_5_4_i_fu_779_p3;
                storemerge37_i_reg_1381 <= storemerge37_i_fu_773_p3;
                storemerge38_i_reg_1393 <= storemerge38_i_fu_789_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_1 = ap_reg_pp0_iter1_empty_n_1_reg_825))) then
                buffer_V_load_8_i_reg_1000 <= buffer_V_load_8_i_fu_317_p3;
                buffer_V_load_9_i_reg_1007 <= buffer_V_load_9_i_fu_323_p3;
                storemerge4_i_reg_958 <= storemerge4_i_fu_269_p3;
                storemerge5_i_reg_965 <= storemerge5_i_fu_275_p3;
                storemerge6_i_reg_972 <= storemerge6_i_fu_285_p3;
                storemerge7_i_reg_979 <= storemerge7_i_fu_291_p3;
                storemerge8_i_reg_986 <= storemerge8_i_fu_301_p3;
                storemerge9_i_reg_993 <= storemerge9_i_fu_307_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (empty_n_1_reg_825 = ap_const_lv1_1))) then
                buffer_V_load_i_reg_909 <= buffer_V_load_i_fu_211_p3;
                storemerge1_i_reg_916 <= storemerge1_i_fu_221_p3;
                storemerge2_i_reg_930 <= storemerge2_i_fu_237_p3;
                storemerge3_i_reg_944 <= storemerge3_i_fu_253_p3;
                storemerge_i_reg_902 <= storemerge_i_fu_205_p3;
                tmp_1_i_reg_937 <= tmp_1_i_fu_243_p3;
                tmp_5_i_reg_951 <= tmp_5_i_fu_259_p3;
                tmp_i_reg_923 <= tmp_i_fu_227_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_1 = ap_reg_pp0_iter11_empty_n_1_reg_825))) then
                tmp_data_V_reg_1411 <= tmp_data_V_fu_819_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_flag00011011, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    MdnStream_V_data_V1_status <= (MdnStream_V_data_V_full_n and MdnStream_V_user_V_full_n and MdnStream_V_last_V_full_n);

    MdnStream_V_data_V1_update_assign_proc : process(ap_enable_reg_pp0_iter13, ap_reg_pp0_iter12_empty_n_1_reg_825, ap_block_pp0_stage0_flag00011001)
    begin
        if (((ap_reg_pp0_iter12_empty_n_1_reg_825 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter13) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then 
            MdnStream_V_data_V1_update <= ap_const_logic_1;
        else 
            MdnStream_V_data_V1_update <= ap_const_logic_0;
        end if; 
    end process;


    MdnStream_V_data_V_blk_n_assign_proc : process(ap_enable_reg_pp0_iter13, ap_reg_pp0_iter12_empty_n_1_reg_825, MdnStream_V_data_V_full_n, ap_block_pp0_stage0_flag00000000)
    begin
        if (((ap_reg_pp0_iter12_empty_n_1_reg_825 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter13) and (ap_block_pp0_stage0_flag00000000 = ap_const_boolean_0))) then 
            MdnStream_V_data_V_blk_n <= MdnStream_V_data_V_full_n;
        else 
            MdnStream_V_data_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    MdnStream_V_data_V_din <= tmp_data_V_reg_1411;
    MdnStream_V_data_V_write <= MdnStream_V_data_V1_update;

    MdnStream_V_last_V_blk_n_assign_proc : process(ap_enable_reg_pp0_iter13, ap_reg_pp0_iter12_empty_n_1_reg_825, MdnStream_V_last_V_full_n, ap_block_pp0_stage0_flag00000000)
    begin
        if (((ap_reg_pp0_iter12_empty_n_1_reg_825 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter13) and (ap_block_pp0_stage0_flag00000000 = ap_const_boolean_0))) then 
            MdnStream_V_last_V_blk_n <= MdnStream_V_last_V_full_n;
        else 
            MdnStream_V_last_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    MdnStream_V_last_V_din <= ap_reg_pp0_iter12_tmp_last_V_reg_897;
    MdnStream_V_last_V_write <= MdnStream_V_data_V1_update;

    MdnStream_V_user_V_blk_n_assign_proc : process(ap_enable_reg_pp0_iter13, ap_reg_pp0_iter12_empty_n_1_reg_825, MdnStream_V_user_V_full_n, ap_block_pp0_stage0_flag00000000)
    begin
        if (((ap_reg_pp0_iter12_empty_n_1_reg_825 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter13) and (ap_block_pp0_stage0_flag00000000 = ap_const_boolean_0))) then 
            MdnStream_V_user_V_blk_n <= MdnStream_V_user_V_full_n;
        else 
            MdnStream_V_user_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    MdnStream_V_user_V_din <= ap_reg_pp0_iter12_tmp_user_V_reg_892;
    MdnStream_V_user_V_write <= MdnStream_V_data_V1_update;

    PxlStream_V_pixel_da0_update_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_flag00011001, ap_condition_502)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = real_start) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_condition_502 = ap_const_boolean_1))) then 
            PxlStream_V_pixel_da0_update <= ap_const_logic_1;
        else 
            PxlStream_V_pixel_da0_update <= ap_const_logic_0;
        end if; 
    end process;

    PxlStream_V_pixel_da_1_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_da_2_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_da_3_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_da_4_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_da_5_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_da_6_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_da_7_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_da_8_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_da_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_la_1_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_la_2_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_la_3_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_la_4_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_la_5_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_la_6_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_la_7_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_la_8_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_la_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_us_1_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_us_2_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_us_3_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_us_4_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_us_5_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_us_6_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_us_7_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_us_8_read <= PxlStream_V_pixel_da0_update;
    PxlStream_V_pixel_us_read <= PxlStream_V_pixel_da0_update;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0_flag00000000 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_flag00001001_assign_proc : process(real_start, ap_done_reg, ap_enable_reg_pp0_iter13, MdnStream_V_data_V1_status, ap_reg_pp0_iter12_empty_n_1_reg_825)
    begin
                ap_block_pp0_stage0_flag00001001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = real_start) and ((ap_const_logic_0 = real_start) or (ap_done_reg = ap_const_logic_1))) or ((ap_const_logic_0 = MdnStream_V_data_V1_status) and (ap_reg_pp0_iter12_empty_n_1_reg_825 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter13)));
    end process;


    ap_block_pp0_stage0_flag00011001_assign_proc : process(real_start, ap_done_reg, ap_enable_reg_pp0_iter13, MdnStream_V_data_V1_status, ap_reg_pp0_iter12_empty_n_1_reg_825)
    begin
                ap_block_pp0_stage0_flag00011001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = real_start) and ((ap_const_logic_0 = real_start) or (ap_done_reg = ap_const_logic_1))) or ((ap_const_logic_0 = MdnStream_V_data_V1_status) and (ap_reg_pp0_iter12_empty_n_1_reg_825 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter13)));
    end process;


    ap_block_pp0_stage0_flag00011011_assign_proc : process(real_start, ap_done_reg, ap_enable_reg_pp0_iter13, MdnStream_V_data_V1_status, ap_reg_pp0_iter12_empty_n_1_reg_825)
    begin
                ap_block_pp0_stage0_flag00011011 <= ((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = real_start) and ((ap_const_logic_0 = real_start) or (ap_done_reg = ap_const_logic_1))) or ((ap_const_logic_0 = MdnStream_V_data_V1_status) and (ap_reg_pp0_iter12_empty_n_1_reg_825 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter13)));
    end process;

        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state14_pp0_stage0_iter13_assign_proc : process(MdnStream_V_data_V1_status, ap_reg_pp0_iter12_empty_n_1_reg_825)
    begin
                ap_block_state14_pp0_stage0_iter13 <= ((ap_const_logic_0 = MdnStream_V_data_V1_status) and (ap_reg_pp0_iter12_empty_n_1_reg_825 = ap_const_lv1_1));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_const_logic_0 = real_start) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_502_assign_proc : process(PxlStream_V_pixel_da_8_empty_n, PxlStream_V_pixel_da_7_empty_n, PxlStream_V_pixel_da_6_empty_n, PxlStream_V_pixel_da_5_empty_n, PxlStream_V_pixel_da_4_empty_n, PxlStream_V_pixel_da_3_empty_n, PxlStream_V_pixel_da_2_empty_n, PxlStream_V_pixel_da_1_empty_n, PxlStream_V_pixel_da_empty_n, PxlStream_V_pixel_us_8_empty_n, PxlStream_V_pixel_us_7_empty_n, PxlStream_V_pixel_us_6_empty_n, PxlStream_V_pixel_us_5_empty_n, PxlStream_V_pixel_us_4_empty_n, PxlStream_V_pixel_us_3_empty_n, PxlStream_V_pixel_us_2_empty_n, PxlStream_V_pixel_us_1_empty_n, PxlStream_V_pixel_us_empty_n, PxlStream_V_pixel_la_8_empty_n, PxlStream_V_pixel_la_7_empty_n, PxlStream_V_pixel_la_6_empty_n, PxlStream_V_pixel_la_5_empty_n, PxlStream_V_pixel_la_4_empty_n, PxlStream_V_pixel_la_3_empty_n, PxlStream_V_pixel_la_2_empty_n, PxlStream_V_pixel_la_1_empty_n, PxlStream_V_pixel_la_empty_n)
    begin
                ap_condition_502 <= (ap_const_logic_1 = (PxlStream_V_pixel_da_8_empty_n and PxlStream_V_pixel_da_7_empty_n and PxlStream_V_pixel_da_6_empty_n and PxlStream_V_pixel_da_5_empty_n and PxlStream_V_pixel_da_4_empty_n and PxlStream_V_pixel_da_3_empty_n and PxlStream_V_pixel_da_2_empty_n and PxlStream_V_pixel_da_1_empty_n and PxlStream_V_pixel_da_empty_n and PxlStream_V_pixel_us_8_empty_n and PxlStream_V_pixel_us_7_empty_n and PxlStream_V_pixel_us_6_empty_n and PxlStream_V_pixel_us_5_empty_n and PxlStream_V_pixel_us_4_empty_n and PxlStream_V_pixel_us_3_empty_n and PxlStream_V_pixel_us_2_empty_n and PxlStream_V_pixel_us_1_empty_n and PxlStream_V_pixel_us_empty_n and PxlStream_V_pixel_la_8_empty_n and PxlStream_V_pixel_la_7_empty_n and PxlStream_V_pixel_la_6_empty_n and PxlStream_V_pixel_la_5_empty_n and PxlStream_V_pixel_la_4_empty_n and PxlStream_V_pixel_la_3_empty_n and PxlStream_V_pixel_la_2_empty_n and PxlStream_V_pixel_la_1_empty_n and PxlStream_V_pixel_la_empty_n));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_flag00011001)
    begin
        if (((ap_const_logic_1 = ap_enable_reg_pp0_iter13) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= real_start;

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_const_logic_0 = real_start) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_idle_pp0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13)
    begin
        if (((ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2) and (ap_const_logic_0 = ap_enable_reg_pp0_iter3) and (ap_const_logic_0 = ap_enable_reg_pp0_iter4) and (ap_const_logic_0 = ap_enable_reg_pp0_iter5) and (ap_const_logic_0 = ap_enable_reg_pp0_iter6) and (ap_const_logic_0 = ap_enable_reg_pp0_iter7) and (ap_const_logic_0 = ap_enable_reg_pp0_iter8) and (ap_const_logic_0 = ap_enable_reg_pp0_iter9) and (ap_const_logic_0 = ap_enable_reg_pp0_iter10) and (ap_const_logic_0 = ap_enable_reg_pp0_iter11) and (ap_const_logic_0 = ap_enable_reg_pp0_iter12) and (ap_const_logic_0 = ap_enable_reg_pp0_iter13))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to12_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12)
    begin
        if (((ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2) and (ap_const_logic_0 = ap_enable_reg_pp0_iter3) and (ap_const_logic_0 = ap_enable_reg_pp0_iter4) and (ap_const_logic_0 = ap_enable_reg_pp0_iter5) and (ap_const_logic_0 = ap_enable_reg_pp0_iter6) and (ap_const_logic_0 = ap_enable_reg_pp0_iter7) and (ap_const_logic_0 = ap_enable_reg_pp0_iter8) and (ap_const_logic_0 = ap_enable_reg_pp0_iter9) and (ap_const_logic_0 = ap_enable_reg_pp0_iter10) and (ap_const_logic_0 = ap_enable_reg_pp0_iter11) and (ap_const_logic_0 = ap_enable_reg_pp0_iter12))) then 
            ap_idle_pp0_0to12 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to12 <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    ap_reset_idle_pp0_assign_proc : process(real_start, ap_idle_pp0_0to12)
    begin
        if (((ap_const_logic_0 = real_start) and (ap_const_logic_1 = ap_idle_pp0_0to12))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    buffer_V_load_11_1_i_fu_467_p3 <= 
        ap_reg_pp0_iter4_storemerge10_i_reg_1014 when (tmp_20_1_i_fu_457_p2(0) = '1') else 
        storemerge14_i_reg_1070;
    buffer_V_load_11_2_i_fu_595_p3 <= 
        ap_reg_pp0_iter6_storemerge18_i_reg_1126 when (tmp_20_2_i_fu_585_p2(0) = '1') else 
        storemerge22_i_reg_1182;
    buffer_V_load_11_3_i_fu_711_p3 <= 
        ap_reg_pp0_iter8_storemerge26_i_reg_1237 when (tmp_20_3_i_fu_707_p2(0) = '1') else 
        storemerge30_i_reg_1291;
    buffer_V_load_11_i_fu_339_p3 <= 
        ap_reg_pp0_iter2_buffer_V_load_i_reg_909 when (tmp_20_i_fu_329_p2(0) = '1') else 
        storemerge4_i_reg_958;
    buffer_V_load_13_1_i_fu_483_p3 <= 
        buffer_V_load_3_1_i_reg_1077 when (tmp_21_1_i_fu_473_p2(0) = '1') else 
        storemerge15_i_reg_1084;
    buffer_V_load_13_2_i_fu_611_p3 <= 
        buffer_V_load_3_2_i_reg_1189 when (tmp_21_2_i_fu_601_p2(0) = '1') else 
        storemerge23_i_reg_1196;
    buffer_V_load_13_3_i_fu_727_p3 <= 
        buffer_V_load_3_3_i_reg_1297 when (tmp_21_3_i_fu_717_p2(0) = '1') else 
        storemerge31_i_reg_1304;
    buffer_V_load_13_4_i_fu_799_p3 <= 
        buffer_V_load_3_4_i_reg_1375 when (tmp_21_4_i_fu_795_p2(0) = '1') else 
        storemerge37_i_reg_1381;
    buffer_V_load_13_i_fu_355_p3 <= 
        storemerge5_i_reg_965 when (tmp_21_i_fu_345_p2(0) = '1') else 
        storemerge6_i_reg_972;
    buffer_V_load_15_1_i_fu_499_p3 <= 
        buffer_V_load_5_1_i_reg_1091 when (tmp_22_1_i_fu_489_p2(0) = '1') else 
        storemerge16_i_reg_1098;
    buffer_V_load_15_2_i_fu_627_p3 <= 
        buffer_V_load_5_2_i_reg_1203 when (tmp_22_2_i_fu_617_p2(0) = '1') else 
        storemerge24_i_reg_1210;
    buffer_V_load_15_3_i_fu_743_p3 <= 
        buffer_V_load_5_3_i_reg_1311 when (tmp_22_3_i_fu_733_p2(0) = '1') else 
        storemerge32_i_reg_1318;
    buffer_V_load_15_i_fu_371_p3 <= 
        storemerge7_i_reg_979 when (tmp_22_i_fu_361_p2(0) = '1') else 
        storemerge8_i_reg_986;
    buffer_V_load_17_1_i_fu_515_p3 <= 
        buffer_V_load_7_1_i_reg_1105 when (tmp_23_1_i_fu_505_p2(0) = '1') else 
        storemerge17_i_reg_1112;
    buffer_V_load_17_2_i_fu_643_p3 <= 
        buffer_V_load_7_2_i_reg_1217 when (tmp_23_2_i_fu_633_p2(0) = '1') else 
        storemerge25_i_reg_1224;
    buffer_V_load_17_i_fu_387_p3 <= 
        storemerge9_i_reg_993 when (tmp_23_i_fu_377_p2(0) = '1') else 
        buffer_V_load_8_i_reg_1000;
    buffer_V_load_3_1_i_fu_403_p3 <= 
        buffer_V_load_11_i_reg_1021 when (tmp_24_i_fu_393_p2(0) = '1') else 
        storemerge11_i_reg_1028;
    buffer_V_load_3_2_i_fu_531_p3 <= 
        buffer_V_load_11_1_i_reg_1133 when (tmp_24_1_i_fu_521_p2(0) = '1') else 
        storemerge19_i_reg_1140;
    buffer_V_load_3_3_i_fu_659_p3 <= 
        buffer_V_load_11_2_i_reg_1243 when (tmp_24_2_i_fu_649_p2(0) = '1') else 
        storemerge27_i_reg_1250;
    buffer_V_load_3_4_i_fu_763_p3 <= 
        buffer_V_load_11_3_i_reg_1337 when (tmp_24_3_i_fu_759_p2(0) = '1') else 
        storemerge34_i_reg_1343;
    buffer_V_load_5_1_i_fu_419_p3 <= 
        buffer_V_load_13_i_reg_1035 when (tmp_25_i_fu_409_p2(0) = '1') else 
        storemerge12_i_reg_1042;
    buffer_V_load_5_2_i_fu_547_p3 <= 
        buffer_V_load_13_1_i_reg_1147 when (tmp_25_1_i_fu_537_p2(0) = '1') else 
        storemerge20_i_reg_1154;
    buffer_V_load_5_3_i_fu_675_p3 <= 
        buffer_V_load_13_2_i_reg_1257 when (tmp_25_2_i_fu_665_p2(0) = '1') else 
        storemerge28_i_reg_1264;
    buffer_V_load_5_4_i_fu_779_p3 <= 
        buffer_V_load_13_3_i_reg_1349 when (tmp_25_3_i_fu_769_p2(0) = '1') else 
        storemerge35_i_reg_1356;
    buffer_V_load_7_1_i_fu_435_p3 <= 
        buffer_V_load_15_i_reg_1049 when (tmp_26_i_fu_425_p2(0) = '1') else 
        storemerge13_i_reg_1056;
    buffer_V_load_7_2_i_fu_563_p3 <= 
        buffer_V_load_15_1_i_reg_1161 when (tmp_26_1_i_fu_553_p2(0) = '1') else 
        storemerge21_i_reg_1168;
    buffer_V_load_7_3_i_fu_691_p3 <= 
        buffer_V_load_15_2_i_reg_1271 when (tmp_26_2_i_fu_681_p2(0) = '1') else 
        storemerge29_i_reg_1278;
    buffer_V_load_8_i_fu_317_p3 <= 
        ap_reg_pp0_iter1_tmp_pixel_data_V_2_2_reg_885 when (tmp_10_i_fu_313_p2(0) = '1') else 
        storemerge3_i_reg_944;
    buffer_V_load_9_1_i_fu_451_p3 <= 
        buffer_V_load_17_i_reg_1063 when (tmp_27_i_fu_441_p2(0) = '1') else 
        ap_reg_pp0_iter3_buffer_V_load_9_i_reg_1007;
    buffer_V_load_9_2_i_fu_579_p3 <= 
        buffer_V_load_17_1_i_reg_1175 when (tmp_27_1_i_fu_569_p2(0) = '1') else 
        ap_reg_pp0_iter5_buffer_V_load_9_1_i_reg_1119;
    buffer_V_load_9_i_fu_323_p3 <= 
        storemerge3_i_reg_944 when (tmp_10_i_fu_313_p2(0) = '1') else 
        ap_reg_pp0_iter1_tmp_pixel_data_V_2_2_reg_885;
    buffer_V_load_i_fu_211_p3 <= 
        tmp_pixel_data_V_0_1_reg_836 when (tmp_2_i_fu_201_p2(0) = '1') else 
        tmp_pixel_data_V_0_0_reg_829;
    empty_n_nbread_fu_82_p28_0 <= (0=>(PxlStream_V_pixel_da_8_empty_n and PxlStream_V_pixel_da_7_empty_n and PxlStream_V_pixel_da_6_empty_n and PxlStream_V_pixel_da_5_empty_n and PxlStream_V_pixel_da_4_empty_n and PxlStream_V_pixel_da_3_empty_n and PxlStream_V_pixel_da_2_empty_n and PxlStream_V_pixel_da_1_empty_n and PxlStream_V_pixel_da_empty_n and PxlStream_V_pixel_us_8_empty_n and PxlStream_V_pixel_us_7_empty_n and PxlStream_V_pixel_us_6_empty_n and PxlStream_V_pixel_us_5_empty_n and PxlStream_V_pixel_us_4_empty_n and PxlStream_V_pixel_us_3_empty_n and PxlStream_V_pixel_us_2_empty_n and PxlStream_V_pixel_us_1_empty_n and PxlStream_V_pixel_us_empty_n and PxlStream_V_pixel_la_8_empty_n and PxlStream_V_pixel_la_7_empty_n and PxlStream_V_pixel_la_6_empty_n and PxlStream_V_pixel_la_5_empty_n and PxlStream_V_pixel_la_4_empty_n and PxlStream_V_pixel_la_3_empty_n and PxlStream_V_pixel_la_2_empty_n and PxlStream_V_pixel_la_1_empty_n and PxlStream_V_pixel_la_empty_n), others=>'-');

    internal_ap_ready_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_flag00011001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = real_start) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n)
    begin
        if ((ap_const_logic_0 = start_full_n)) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, internal_ap_ready, start_once_reg)
    begin
        if (((ap_const_logic_1 = real_start) and ((ap_const_logic_1 = internal_ap_ready) or (ap_const_logic_0 = start_once_reg)))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    storemerge10_i_fu_333_p3 <= 
        storemerge4_i_reg_958 when (tmp_20_i_fu_329_p2(0) = '1') else 
        ap_reg_pp0_iter2_buffer_V_load_i_reg_909;
    storemerge11_i_fu_349_p3 <= 
        storemerge6_i_reg_972 when (tmp_21_i_fu_345_p2(0) = '1') else 
        storemerge5_i_reg_965;
    storemerge12_i_fu_365_p3 <= 
        storemerge8_i_reg_986 when (tmp_22_i_fu_361_p2(0) = '1') else 
        storemerge7_i_reg_979;
    storemerge13_i_fu_381_p3 <= 
        buffer_V_load_8_i_reg_1000 when (tmp_23_i_fu_377_p2(0) = '1') else 
        storemerge9_i_reg_993;
    storemerge14_i_fu_397_p3 <= 
        storemerge11_i_reg_1028 when (tmp_24_i_fu_393_p2(0) = '1') else 
        buffer_V_load_11_i_reg_1021;
    storemerge15_i_fu_413_p3 <= 
        storemerge12_i_reg_1042 when (tmp_25_i_fu_409_p2(0) = '1') else 
        buffer_V_load_13_i_reg_1035;
    storemerge16_i_fu_429_p3 <= 
        storemerge13_i_reg_1056 when (tmp_26_i_fu_425_p2(0) = '1') else 
        buffer_V_load_15_i_reg_1049;
    storemerge17_i_fu_445_p3 <= 
        ap_reg_pp0_iter3_buffer_V_load_9_i_reg_1007 when (tmp_27_i_fu_441_p2(0) = '1') else 
        buffer_V_load_17_i_reg_1063;
    storemerge18_i_fu_461_p3 <= 
        storemerge14_i_reg_1070 when (tmp_20_1_i_fu_457_p2(0) = '1') else 
        ap_reg_pp0_iter4_storemerge10_i_reg_1014;
    storemerge19_i_fu_477_p3 <= 
        storemerge15_i_reg_1084 when (tmp_21_1_i_fu_473_p2(0) = '1') else 
        buffer_V_load_3_1_i_reg_1077;
    storemerge1_i_fu_221_p3 <= 
        tmp_pixel_data_V_0_2_reg_843 when (tmp_8_i_fu_217_p2(0) = '1') else 
        tmp_pixel_data_V_1_0_reg_850;
    storemerge20_i_fu_493_p3 <= 
        storemerge16_i_reg_1098 when (tmp_22_1_i_fu_489_p2(0) = '1') else 
        buffer_V_load_5_1_i_reg_1091;
    storemerge21_i_fu_509_p3 <= 
        storemerge17_i_reg_1112 when (tmp_23_1_i_fu_505_p2(0) = '1') else 
        buffer_V_load_7_1_i_reg_1105;
    storemerge22_i_fu_525_p3 <= 
        storemerge19_i_reg_1140 when (tmp_24_1_i_fu_521_p2(0) = '1') else 
        buffer_V_load_11_1_i_reg_1133;
    storemerge23_i_fu_541_p3 <= 
        storemerge20_i_reg_1154 when (tmp_25_1_i_fu_537_p2(0) = '1') else 
        buffer_V_load_13_1_i_reg_1147;
    storemerge24_i_fu_557_p3 <= 
        storemerge21_i_reg_1168 when (tmp_26_1_i_fu_553_p2(0) = '1') else 
        buffer_V_load_15_1_i_reg_1161;
    storemerge25_i_fu_573_p3 <= 
        ap_reg_pp0_iter5_buffer_V_load_9_1_i_reg_1119 when (tmp_27_1_i_fu_569_p2(0) = '1') else 
        buffer_V_load_17_1_i_reg_1175;
    storemerge26_i_fu_589_p3 <= 
        storemerge22_i_reg_1182 when (tmp_20_2_i_fu_585_p2(0) = '1') else 
        ap_reg_pp0_iter6_storemerge18_i_reg_1126;
    storemerge27_i_fu_605_p3 <= 
        storemerge23_i_reg_1196 when (tmp_21_2_i_fu_601_p2(0) = '1') else 
        buffer_V_load_3_2_i_reg_1189;
    storemerge28_i_fu_621_p3 <= 
        storemerge24_i_reg_1210 when (tmp_22_2_i_fu_617_p2(0) = '1') else 
        buffer_V_load_5_2_i_reg_1203;
    storemerge29_i_fu_637_p3 <= 
        storemerge25_i_reg_1224 when (tmp_23_2_i_fu_633_p2(0) = '1') else 
        buffer_V_load_7_2_i_reg_1217;
    storemerge2_i_fu_237_p3 <= 
        tmp_pixel_data_V_1_1_reg_857 when (tmp_4_i_fu_233_p2(0) = '1') else 
        tmp_pixel_data_V_1_2_reg_864;
    storemerge30_i_fu_653_p3 <= 
        storemerge27_i_reg_1250 when (tmp_24_2_i_fu_649_p2(0) = '1') else 
        buffer_V_load_11_2_i_reg_1243;
    storemerge31_i_fu_669_p3 <= 
        storemerge28_i_reg_1264 when (tmp_25_2_i_fu_665_p2(0) = '1') else 
        buffer_V_load_13_2_i_reg_1257;
    storemerge32_i_fu_685_p3 <= 
        storemerge29_i_reg_1278 when (tmp_26_2_i_fu_681_p2(0) = '1') else 
        buffer_V_load_15_2_i_reg_1271;
    storemerge33_i_fu_701_p3 <= 
        ap_reg_pp0_iter7_buffer_V_load_9_2_i_reg_1231 when (tmp_27_2_i_fu_697_p2(0) = '1') else 
        buffer_V_load_17_2_i_reg_1285;
    storemerge34_i_fu_721_p3 <= 
        storemerge31_i_reg_1304 when (tmp_21_3_i_fu_717_p2(0) = '1') else 
        buffer_V_load_3_3_i_reg_1297;
    storemerge35_i_fu_737_p3 <= 
        storemerge32_i_reg_1318 when (tmp_22_3_i_fu_733_p2(0) = '1') else 
        buffer_V_load_5_3_i_reg_1311;
    storemerge36_i_fu_753_p3 <= 
        storemerge33_i_reg_1331 when (tmp_23_3_i_fu_749_p2(0) = '1') else 
        buffer_V_load_7_3_i_reg_1325;
    storemerge37_i_fu_773_p3 <= 
        storemerge35_i_reg_1356 when (tmp_25_3_i_fu_769_p2(0) = '1') else 
        buffer_V_load_13_3_i_reg_1349;
    storemerge38_i_fu_789_p3 <= 
        storemerge36_i_reg_1369 when (tmp_26_3_i_fu_785_p2(0) = '1') else 
        buffer_V_load_15_3_i_reg_1363;
    storemerge39_i_fu_809_p3 <= 
        storemerge38_i_reg_1393 when (tmp_22_4_i_fu_805_p2(0) = '1') else 
        buffer_V_load_5_4_i_reg_1387;
    storemerge3_i_fu_253_p3 <= 
        tmp_pixel_data_V_2_0_reg_871 when (tmp_3_i_fu_249_p2(0) = '1') else 
        tmp_pixel_data_V_2_1_reg_878;
    storemerge4_i_fu_269_p3 <= 
        tmp_i_reg_923 when (tmp_6_i_fu_265_p2(0) = '1') else 
        storemerge_i_reg_902;
    storemerge5_i_fu_275_p3 <= 
        storemerge_i_reg_902 when (tmp_6_i_fu_265_p2(0) = '1') else 
        tmp_i_reg_923;
    storemerge6_i_fu_285_p3 <= 
        tmp_1_i_reg_937 when (tmp_7_i_fu_281_p2(0) = '1') else 
        storemerge1_i_reg_916;
    storemerge7_i_fu_291_p3 <= 
        storemerge1_i_reg_916 when (tmp_7_i_fu_281_p2(0) = '1') else 
        tmp_1_i_reg_937;
    storemerge8_i_fu_301_p3 <= 
        tmp_5_i_reg_951 when (tmp_9_i_fu_297_p2(0) = '1') else 
        storemerge2_i_reg_930;
    storemerge9_i_fu_307_p3 <= 
        storemerge2_i_reg_930 when (tmp_9_i_fu_297_p2(0) = '1') else 
        tmp_5_i_reg_951;
    storemerge_i_fu_205_p3 <= 
        tmp_pixel_data_V_0_0_reg_829 when (tmp_2_i_fu_201_p2(0) = '1') else 
        tmp_pixel_data_V_0_1_reg_836;
    tmp_10_i_fu_313_p2 <= "1" when (unsigned(storemerge3_i_reg_944) > unsigned(ap_reg_pp0_iter1_tmp_pixel_data_V_2_2_reg_885)) else "0";
    tmp_1_i_fu_243_p3 <= 
        tmp_pixel_data_V_1_2_reg_864 when (tmp_4_i_fu_233_p2(0) = '1') else 
        tmp_pixel_data_V_1_1_reg_857;
    tmp_20_1_i_fu_457_p2 <= "1" when (unsigned(ap_reg_pp0_iter4_storemerge10_i_reg_1014) > unsigned(storemerge14_i_reg_1070)) else "0";
    tmp_20_2_i_fu_585_p2 <= "1" when (unsigned(ap_reg_pp0_iter6_storemerge18_i_reg_1126) > unsigned(storemerge22_i_reg_1182)) else "0";
    tmp_20_3_i_fu_707_p2 <= "1" when (unsigned(ap_reg_pp0_iter8_storemerge26_i_reg_1237) > unsigned(storemerge30_i_reg_1291)) else "0";
    tmp_20_i_fu_329_p2 <= "1" when (unsigned(ap_reg_pp0_iter2_buffer_V_load_i_reg_909) > unsigned(storemerge4_i_reg_958)) else "0";
    tmp_21_1_i_fu_473_p2 <= "1" when (unsigned(buffer_V_load_3_1_i_reg_1077) > unsigned(storemerge15_i_reg_1084)) else "0";
    tmp_21_2_i_fu_601_p2 <= "1" when (unsigned(buffer_V_load_3_2_i_reg_1189) > unsigned(storemerge23_i_reg_1196)) else "0";
    tmp_21_3_i_fu_717_p2 <= "1" when (unsigned(buffer_V_load_3_3_i_reg_1297) > unsigned(storemerge31_i_reg_1304)) else "0";
    tmp_21_4_i_fu_795_p2 <= "1" when (unsigned(buffer_V_load_3_4_i_reg_1375) > unsigned(storemerge37_i_reg_1381)) else "0";
    tmp_21_i_fu_345_p2 <= "1" when (unsigned(storemerge5_i_reg_965) > unsigned(storemerge6_i_reg_972)) else "0";
    tmp_22_1_i_fu_489_p2 <= "1" when (unsigned(buffer_V_load_5_1_i_reg_1091) > unsigned(storemerge16_i_reg_1098)) else "0";
    tmp_22_2_i_fu_617_p2 <= "1" when (unsigned(buffer_V_load_5_2_i_reg_1203) > unsigned(storemerge24_i_reg_1210)) else "0";
    tmp_22_3_i_fu_733_p2 <= "1" when (unsigned(buffer_V_load_5_3_i_reg_1311) > unsigned(storemerge32_i_reg_1318)) else "0";
    tmp_22_4_i_fu_805_p2 <= "1" when (unsigned(buffer_V_load_5_4_i_reg_1387) > unsigned(storemerge38_i_reg_1393)) else "0";
    tmp_22_i_fu_361_p2 <= "1" when (unsigned(storemerge7_i_reg_979) > unsigned(storemerge8_i_reg_986)) else "0";
    tmp_23_1_i_fu_505_p2 <= "1" when (unsigned(buffer_V_load_7_1_i_reg_1105) > unsigned(storemerge17_i_reg_1112)) else "0";
    tmp_23_2_i_fu_633_p2 <= "1" when (unsigned(buffer_V_load_7_2_i_reg_1217) > unsigned(storemerge25_i_reg_1224)) else "0";
    tmp_23_3_i_fu_749_p2 <= "1" when (unsigned(buffer_V_load_7_3_i_reg_1325) > unsigned(storemerge33_i_reg_1331)) else "0";
    tmp_23_i_fu_377_p2 <= "1" when (unsigned(storemerge9_i_reg_993) > unsigned(buffer_V_load_8_i_reg_1000)) else "0";
    tmp_24_1_i_fu_521_p2 <= "1" when (unsigned(buffer_V_load_11_1_i_reg_1133) > unsigned(storemerge19_i_reg_1140)) else "0";
    tmp_24_2_i_fu_649_p2 <= "1" when (unsigned(buffer_V_load_11_2_i_reg_1243) > unsigned(storemerge27_i_reg_1250)) else "0";
    tmp_24_3_i_fu_759_p2 <= "1" when (unsigned(buffer_V_load_11_3_i_reg_1337) > unsigned(storemerge34_i_reg_1343)) else "0";
    tmp_24_i_fu_393_p2 <= "1" when (unsigned(buffer_V_load_11_i_reg_1021) > unsigned(storemerge11_i_reg_1028)) else "0";
    tmp_25_1_i_fu_537_p2 <= "1" when (unsigned(buffer_V_load_13_1_i_reg_1147) > unsigned(storemerge20_i_reg_1154)) else "0";
    tmp_25_2_i_fu_665_p2 <= "1" when (unsigned(buffer_V_load_13_2_i_reg_1257) > unsigned(storemerge28_i_reg_1264)) else "0";
    tmp_25_3_i_fu_769_p2 <= "1" when (unsigned(buffer_V_load_13_3_i_reg_1349) > unsigned(storemerge35_i_reg_1356)) else "0";
    tmp_25_4_i_fu_815_p2 <= "1" when (unsigned(buffer_V_load_13_4_i_reg_1399) > unsigned(storemerge39_i_reg_1405)) else "0";
    tmp_25_i_fu_409_p2 <= "1" when (unsigned(buffer_V_load_13_i_reg_1035) > unsigned(storemerge12_i_reg_1042)) else "0";
    tmp_26_1_i_fu_553_p2 <= "1" when (unsigned(buffer_V_load_15_1_i_reg_1161) > unsigned(storemerge21_i_reg_1168)) else "0";
    tmp_26_2_i_fu_681_p2 <= "1" when (unsigned(buffer_V_load_15_2_i_reg_1271) > unsigned(storemerge29_i_reg_1278)) else "0";
    tmp_26_3_i_fu_785_p2 <= "1" when (unsigned(buffer_V_load_15_3_i_reg_1363) > unsigned(storemerge36_i_reg_1369)) else "0";
    tmp_26_i_fu_425_p2 <= "1" when (unsigned(buffer_V_load_15_i_reg_1049) > unsigned(storemerge13_i_reg_1056)) else "0";
    tmp_27_1_i_fu_569_p2 <= "1" when (unsigned(buffer_V_load_17_1_i_reg_1175) > unsigned(ap_reg_pp0_iter5_buffer_V_load_9_1_i_reg_1119)) else "0";
    tmp_27_2_i_fu_697_p2 <= "1" when (unsigned(buffer_V_load_17_2_i_reg_1285) > unsigned(ap_reg_pp0_iter7_buffer_V_load_9_2_i_reg_1231)) else "0";
    tmp_27_i_fu_441_p2 <= "1" when (unsigned(buffer_V_load_17_i_reg_1063) > unsigned(ap_reg_pp0_iter3_buffer_V_load_9_i_reg_1007)) else "0";
    tmp_2_i_fu_201_p2 <= "1" when (unsigned(tmp_pixel_data_V_0_0_reg_829) > unsigned(tmp_pixel_data_V_0_1_reg_836)) else "0";
    tmp_3_i_fu_249_p2 <= "1" when (unsigned(tmp_pixel_data_V_2_0_reg_871) > unsigned(tmp_pixel_data_V_2_1_reg_878)) else "0";
    tmp_4_i_fu_233_p2 <= "1" when (unsigned(tmp_pixel_data_V_1_1_reg_857) > unsigned(tmp_pixel_data_V_1_2_reg_864)) else "0";
    tmp_5_i_fu_259_p3 <= 
        tmp_pixel_data_V_2_1_reg_878 when (tmp_3_i_fu_249_p2(0) = '1') else 
        tmp_pixel_data_V_2_0_reg_871;
    tmp_6_i_fu_265_p2 <= "1" when (unsigned(storemerge_i_reg_902) > unsigned(tmp_i_reg_923)) else "0";
    tmp_7_i_fu_281_p2 <= "1" when (unsigned(storemerge1_i_reg_916) > unsigned(tmp_1_i_reg_937)) else "0";
    tmp_8_i_fu_217_p2 <= "1" when (unsigned(tmp_pixel_data_V_0_2_reg_843) > unsigned(tmp_pixel_data_V_1_0_reg_850)) else "0";
    tmp_9_i_fu_297_p2 <= "1" when (unsigned(storemerge2_i_reg_930) > unsigned(tmp_5_i_reg_951)) else "0";
    tmp_data_V_fu_819_p3 <= 
        buffer_V_load_13_4_i_reg_1399 when (tmp_25_4_i_fu_815_p2(0) = '1') else 
        storemerge39_i_reg_1405;
    tmp_i_fu_227_p3 <= 
        tmp_pixel_data_V_1_0_reg_850 when (tmp_8_i_fu_217_p2(0) = '1') else 
        tmp_pixel_data_V_0_2_reg_843;
end behav;
