// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XSTPG_H
#define XSTPG_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xstpg_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XStpg_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XStpg;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XStpg_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XStpg_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XStpg_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XStpg_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XStpg_Initialize(XStpg *InstancePtr, u16 DeviceId);
XStpg_Config* XStpg_LookupConfig(u16 DeviceId);
int XStpg_CfgInitialize(XStpg *InstancePtr, XStpg_Config *ConfigPtr);
#else
int XStpg_Initialize(XStpg *InstancePtr, const char* InstanceName);
int XStpg_Release(XStpg *InstancePtr);
#endif

void XStpg_Start(XStpg *InstancePtr);
u32 XStpg_IsDone(XStpg *InstancePtr);
u32 XStpg_IsIdle(XStpg *InstancePtr);
u32 XStpg_IsReady(XStpg *InstancePtr);
void XStpg_EnableAutoRestart(XStpg *InstancePtr);
void XStpg_DisableAutoRestart(XStpg *InstancePtr);

void XStpg_Set_width_V(XStpg *InstancePtr, u32 Data);
u32 XStpg_Get_width_V(XStpg *InstancePtr);
void XStpg_Set_height_V(XStpg *InstancePtr, u32 Data);
u32 XStpg_Get_height_V(XStpg *InstancePtr);

void XStpg_InterruptGlobalEnable(XStpg *InstancePtr);
void XStpg_InterruptGlobalDisable(XStpg *InstancePtr);
void XStpg_InterruptEnable(XStpg *InstancePtr, u32 Mask);
void XStpg_InterruptDisable(XStpg *InstancePtr, u32 Mask);
void XStpg_InterruptClear(XStpg *InstancePtr, u32 Mask);
u32 XStpg_InterruptGetEnabled(XStpg *InstancePtr);
u32 XStpg_InterruptGetStatus(XStpg *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
